import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "ari-lac",
  away: {
    name: "Arizona Cardinals",
    abbr: "ARI",
    color: "#97233F",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Arizona's 4-3 is built around Budda Baker (85 OVR) as the heartbeat safety who plays near the box. Josh Sweat (84 OVR) provides edge pressure from the SAM spot. Byron Murphy (82 OVR) plays the nickel with ball-hawk instincts. Cover 3 zone underneath with Budda as the single-high over the top.",
    offense: {
      WR_LEFT:  { display: "M. Harrison Jr.", initials: "MH", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 87 , headshot: "Harrison Jr._Marvin.jpg" },
      LT:       { display: "P. Johnson Jr.", initials: "PJ", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 82, maxWidth: 36 , headshot: "Johnson Jr._Paris.jpg" },
      LG:       { display: "W. Hernandez", initials: "WH", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 78, maxWidth: 36 , headshot: "Hernandez_Will.jpg" },
      C:        { display: "H. Froholdt", initials: "HF", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 72, maxWidth: 36 , headshot: "Froholdt_Hjalte.jpg" },
      RG:       { display: "J. Pugh", initials: "JP", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 74, maxWidth: 36 , headshot: "Pugh_Justin.jpg" },
      RT:       { display: "K. Beachum", initials: "KB", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 72, maxWidth: 36 , headshot: "Beachum_Kelvin.jpg" },
      TE:       { display: "T. McBride", initials: "TM", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 92, nameBold: true , headshot: "McBride_Trey.jpg" },
      SLOT:     { display: "G. Dortch", initials: "GD", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 73 , headshot: "Dortch_Greg.jpg" },
      WR_RIGHT: { display: "M. Wilson", initials: "MW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 74 , headshot: "Wilson_Michael.jpg" },
      QB:       { display: "K. Murray", initials: "KM", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true , headshot: "Murray_Kyler.jpg" },
      RB:       { display: "E. Demercado", initials: "ED", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 72 , headshot: "Demercado_Emari.jpg" },
    },
    defense: {
      CB_LEFT: { display: "M. Wilson", initials: "MW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 , headshot: "Wilson_Marco.jpg" },
      SS:      { display: "B. Baker", initials: "BB", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 85 , headshot: "Baker_Budda.jpg" },
      FS:      { display: "J. Thompson", initials: "JT", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 80 , headshot: "Thompson_Jalen.jpg" },
      NB:      { display: "B. Murphy Jr.", initials: "BM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 82 , headshot: "Murphy Jr._Byron.jpg" },
      OLB_L:   { display: "J. Sweat", initials: "JS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 84 , headshot: "Sweat_Josh.jpg" },
      ILB_L:   { display: "K. White", initials: "KW", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "White_Kyzir.jpg" },
      ILB_R:   { display: "D. Gardeck", initials: "DG", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 , headshot: "Gardeck_Dennis.jpg" },
      OLB_R:   { display: "Z. Collins", initials: "ZC", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 77 , headshot: "Collins_Zaven.jpg" },
      DE_L:    { display: "D. Fowler Jr.", initials: "DF", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 , headshot: "Fowler Jr._Dante.jpg" },
      NT:      { display: "R. Lopez", initials: "RL", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 , headshot: "Lopez_Roy.jpg" },
      DE_R:    { display: "J. Ledbetter", initials: "JL", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 , headshot: "Ledbetter_Jonathan.jpg" },
    },
  },
  home: {
    name: "Los Angeles Chargers",
    abbr: "LAC",
    color: "#0080C6",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 2 Zone",
    defScheme: "3-4 Base",
    defDescription: "The Chargers' 3-4 is headlined by Khalil Mack (87 OVR) and Joey Bosa (83 OVR) as elite bookend OLBs — one of the most experienced edge tandems in the league. Derwin James (94 OVR) is an elite SS who plays near the line in an aggressive two-deep look. Cover 2 zone with James rotating into the box.",
    offense: {
      WR_LEFT:  { display: "Q. Johnston", initials: "QJ", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 78 , headshot: "Johnston_Quentin.jpg" },
      LT:       { display: "R. Slater", initials: "RS", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 90, maxWidth: 36, nameBold: true , headshot: "Slater_Rashawn.jpg" },
      LG:       { display: "Z. Johnson", initials: "ZJ", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 78, maxWidth: 36 , headshot: "Johnson_Zion.jpg" },
      C:        { display: "B. Bozeman", initials: "BB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 , headshot: "Bozeman_Bradley.jpg" },
      RG:       { display: "J. Salyer", initials: "JS", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 76, maxWidth: 36 , headshot: "Salyer_Jamaree.jpg" },
      RT:       { display: "T. Pipkins III", initials: "TP", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 74, maxWidth: 36 , headshot: "Pipkins III_Trey.jpg" },
      TE:       { display: "W. Dissly", initials: "WD", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 74 , headshot: "Dissly_Will.jpg" },
      SLOT:     { display: "L. McConkey", initials: "LM", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 84 , headshot: "McConkey_Ladd.jpg" },
      WR_RIGHT: { display: "J. Palmer", initials: "JP", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 76 , headshot: "Palmer_Joshua.jpg" },
      QB:       { display: "J. Herbert", initials: "JH", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 89, nameBold: true , headshot: "Herbert_Justin.jpg" },
      RB:       { display: "J. Dobbins", initials: "JD", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 79 , headshot: "Dobbins_J.K..jpg" },
    },
    defense: {
      CB_LEFT: { display: "A. Samuel Jr.", initials: "AS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 80 , headshot: "Samuel Jr._Asante.jpg" },
      SS:      { display: "D. James", initials: "DJ", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 94, nameBold: true , headshot: "James_Derwin.jpg" },
      FS:      { display: "A. Gilman", initials: "AG", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 , headshot: "Gilman_Alohi.jpg" },
      NB:      { display: "M. Davis", initials: "MD", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 73 , headshot: "Davis_Michael.jpg" },
      OLB_L:   { display: "K. Mack", initials: "KM", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 87 , headshot: "Mack_Khalil.jpg" },
      ILB_L:   { display: "K. Murray Jr.", initials: "KM", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "Murray Jr._Kenneth.jpg" },
      ILB_R:   { display: "D. Henley", initials: "DH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "Henley_Daiyan.jpg" },
      OLB_R:   { display: "J. Bosa", initials: "JB", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 83 , headshot: "Bosa_Joey.jpg" },
      DE_L:    { display: "S. Matlock", initials: "SM", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 , headshot: "Matlock_Scott.jpg" },
      NT:      { display: "A. Johnson", initials: "AJ", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 74 , headshot: "Johnson_Austin.jpg" },
      DE_R:    { display: "O. Ogbonnia", initials: "OO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 , headshot: "Ogbonnia_Otito.jpg" },
    },
  },
  matchupSummary: {
    grades: [
      {
        label: "Pass Protection",
        awayGrade: "C-",
        homeGrade: "A",
        note: "K. Mack (87) + J. Bosa (83) vs ARI's OLine — most one-sided pass rush matchup on the slate per analyst consensus",
      },
      {
        label: "TE Matchup",
        awayGrade: "A",
        homeGrade: "C-",
        note: "T. McBride (92) creates mismatches vs K. Murray Jr. (76) — TE vs linebacker coverage",
      },
      {
        label: "WR1 vs CB1",
        awayGrade: "A",
        homeGrade: "C-",
        note: "M. Harrison Jr. (87) vs A. Samuel Jr. (80) — ARI's best weapon vs LAC's CB1; Harrison has to win this if ARI has any shot",
      },
      {
        label: "QB vs Pass Rush",
        awayGrade: "C-",
        homeGrade: "A",
        note: "J. Herbert (89) vs J. Sweat (84) — QB faces elite edge pressure",
      },
      {
        label: "Slot Matchup",
        awayGrade: "C+",
        homeGrade: "B",
        note: "L. McConkey (84) vs B. Murphy Jr. (82) — slot matchup in the middle of the field",
      },
    ],
    verdict: "Largest spread of the week — LAC's Mack/Bosa/James triple threat too much; Chargers win by 17+",
  },
};
