import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "ari-lac",
  away: {
    name: "Arizona Cardinals",
    abbr: "ARI",
    color: "#97233F",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "M. Harrison Jr.", initials: "MH", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 87 },
      LT:       { display: "P. Johnson Jr.", initials: "PJ", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 82, maxWidth: 36 },
      LG:       { display: "W. Hernandez", initials: "WH", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 78, maxWidth: 36 },
      C:        { display: "H. Froholdt", initials: "HF", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 72, maxWidth: 36 },
      RG:       { display: "J. Pugh", initials: "JP", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 74, maxWidth: 36 },
      RT:       { display: "K. Beachum", initials: "KB", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 72, maxWidth: 36 },
      TE:       { display: "T. McBride", initials: "TM", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 92, nameBold: true },
      SLOT:     { display: "G. Dortch", initials: "GD", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 73 },
      WR_RIGHT: { display: "M. Wilson", initials: "MW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 74 },
      QB:       { display: "K. Murray", initials: "KM", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true },
      RB:       { display: "E. Demercado", initials: "ED", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 72 },
    },
    defense: {
      CB_LEFT: { display: "M. Wilson", initials: "MW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      SS:      { display: "B. Baker", initials: "BB", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 85 },
      FS:      { display: "J. Thompson", initials: "JT", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 80 },
      NB:      { display: "B. Murphy Jr.", initials: "BM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 82 },
      OLB_L:   { display: "J. Sweat", initials: "JS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 84 },
      ILB_L:   { display: "K. White", initials: "KW", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      ILB_R:   { display: "D. Gardeck", initials: "DG", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 },
      OLB_R:   { display: "Z. Collins", initials: "ZC", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 77 },
      DE_L:    { display: "D. Fowler Jr.", initials: "DF", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
      NT:      { display: "R. Lopez", initials: "RL", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 },
      DE_R:    { display: "J. Ledbetter", initials: "JL", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
    },
  },
  home: {
    name: "Los Angeles Chargers",
    abbr: "LAC",
    color: "#0080C6",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 2 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "Q. Johnston", initials: "QJ", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 78 },
      LT:       { display: "R. Slater", initials: "RS", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 90, maxWidth: 36, nameBold: true },
      LG:       { display: "Z. Johnson", initials: "ZJ", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 78, maxWidth: 36 },
      C:        { display: "B. Bozeman", initials: "BB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "J. Salyer", initials: "JS", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 76, maxWidth: 36 },
      RT:       { display: "T. Pipkins III", initials: "TP", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 74, maxWidth: 36 },
      TE:       { display: "W. Dissly", initials: "WD", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 74 },
      SLOT:     { display: "L. McConkey", initials: "LM", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 84 },
      WR_RIGHT: { display: "J. Palmer", initials: "JP", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 76 },
      QB:       { display: "J. Herbert", initials: "JH", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 89, nameBold: true },
      RB:       { display: "J. Dobbins", initials: "JD", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 79 },
    },
    defense: {
      CB_LEFT: { display: "A. Samuel Jr.", initials: "AS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 80 },
      SS:      { display: "D. James", initials: "DJ", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 94, nameBold: true },
      FS:      { display: "A. Gilman", initials: "AG", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 },
      NB:      { display: "M. Davis", initials: "MD", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 73 },
      OLB_L:   { display: "K. Mack", initials: "KM", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 87 },
      ILB_L:   { display: "K. Murray Jr.", initials: "KM", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      ILB_R:   { display: "D. Henley", initials: "DH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      OLB_R:   { display: "J. Bosa", initials: "JB", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 83 },
      DE_L:    { display: "S. Matlock", initials: "SM", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
      NT:      { display: "A. Johnson", initials: "AJ", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 74 },
      DE_R:    { display: "O. Ogbonnia", initials: "OO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
    },
  },
};
