import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "atl-pit",
  away: {
    name: "Atlanta Falcons",
    abbr: "ATL",
    color: "#A71930",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Atlanta's 4-3 relies on A.J. Terrell (86 OVR) as its best cover corner and Jessie Bates III (88 OVR) as the centerfield safety. Arnold Ebiketie and James Pearce Jr. provide edge pressure off the perimeter. Cover 3 zone with Kaden Elliss and Troy Andersen as active interior linebackers.",
    offense: {
      WR_LEFT:  { display: "D. London", initials: "DL", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 91, nameBold: true , headshot: "London_Drake.jpg" },
      LT:       { display: "J. Matthews", initials: "JM", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 82, maxWidth: 36 , headshot: "Matthews_Jake.jpg" },
      LG:       { display: "M. Bergeron", initials: "MB", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 76, maxWidth: 36 , headshot: "Bergeron_Matthew.jpg" },
      C:        { display: "D. Dalman", initials: "DD", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "C. Lindstrom", initials: "CL", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 94, maxWidth: 36, nameBold: true , headshot: "Lindstrom_Chris.jpg" },
      RT:       { display: "K. McGary", initials: "KM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 79, maxWidth: 36 },
      TE:       { display: "K. Pitts", initials: "KP", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 84 , headshot: "Pitts_Kyle.jpg" },
      SLOT:     { display: "K. Hodge", initials: "KH", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 , headshot: "Hodge_KhaDarel.jpg" },
      WR_RIGHT: { display: "D. Mooney", initials: "DM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 80 , headshot: "Mooney_Darnell.jpg" },
      QB:       { display: "M. Penix Jr.", initials: "MP", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 72, nameBold: true , headshot: "Penix Jr._Michael.jpg" },
      RB:       { display: "B. Robinson", initials: "BR", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 93, nameBold: true , headshot: "Robinson_Bijan.jpg" },
    },
    defense: {
      CB_LEFT: { display: "A. Terrell", initials: "AT", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 86 , headshot: "Terrell_A.J..jpg" },
      SS:      { display: "J. Bates III", initials: "JB", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 88 , headshot: "Bates III_Jessie.jpg" },
      FS:      { display: "D. Hellams", initials: "DH", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 73 , headshot: "Hellams_DeMarcco.jpg" },
      NB:      { display: "J. Okudah", initials: "JO", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 , headshot: "Okudah_Jeff.jpg" },
      OLB_L:   { display: "A. Ebiketie", initials: "AE", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 , headshot: "Ebiketie_Arnold.jpg" },
      ILB_L:   { display: "K. Elliss", initials: "KE", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "Elliss_Kaden.jpg" },
      ILB_R:   { display: "T. Andersen", initials: "TA", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 , headshot: "Andersen_Troy.jpg" },
      OLB_R:   { display: "J. Pearce Jr.", initials: "JP", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 , headshot: "Pearce Jr._James.jpg" },
      DE_L:    { display: "T. Graham", initials: "TG", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 , headshot: "Graham_Ta'Quon.jpg" },
      NT:      { display: "D. Onyemata", initials: "DO", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 78 , headshot: "Onyemata_David.jpg" },
      DE_R:    { display: "R. Orhorhoro", initials: "RO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 , headshot: "Orhorhoro_Ruke.jpg" },
    },
  },
  home: {
    name: "Pittsburgh Steelers",
    abbr: "PIT",
    color: "#FFB612",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 1 Zone Blitz",
    defScheme: "3-4 Base",
    defDescription: "Pittsburgh's 3-4 is legendary. T.J. Watt (99 OVR) is a perennial DPOY candidate off the right edge. Cameron Heyward (94 OVR) remains the best veteran DT in the league. Minkah Fitzpatrick (93 OVR) is a center-field safety with elite instincts. The Steelers run Cover 1 robber and zone blitz packages to maximize their talent.",
    offense: {
      WR_LEFT:  { display: "D. Metcalf", initials: "DM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 85 , headshot: "Metcalf_DK.jpg" },
      LT:       { display: "D. Moore Jr.", initials: "DM", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 76, maxWidth: 36 , headshot: "Moore Jr._Dan.jpg" },
      LG:       { display: "I. Seumalo", initials: "IS", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 83, maxWidth: 36 , headshot: "Seumalo_Isaac.jpg" },
      C:        { display: "N. Herbig", initials: "NH", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 , headshot: "Herbig_Nate.jpg" },
      RG:       { display: "J. Daniels", initials: "JD", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 80, maxWidth: 36 , headshot: "Daniels_James.jpg" },
      RT:       { display: "B. Jones", initials: "BJ", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 78, maxWidth: 36 , headshot: "Jones_Broderick.jpg" },
      TE:       { display: "P. Freiermuth", initials: "PF", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 80 , headshot: "Freiermuth_Pat.jpg" },
      SLOT:     { display: "B. Skowronek", initials: "BS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 , headshot: "Skowronek_Ben.jpg" },
      WR_RIGHT: { display: "V. Jefferson", initials: "VJ", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 73 , headshot: "Jefferson_Van.jpg" },
      QB:       { display: "A. Rodgers", initials: "AR", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 78, nameBold: true , headshot: "Rodgers_Aaron.jpg" },
      RB:       { display: "N. Harris", initials: "NH", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 80 , headshot: "Harris_Najee.jpg" },
    },
    defense: {
      CB_LEFT: { display: "J. Porter Jr.", initials: "JP", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 80 , headshot: "Porter Jr._Joey.jpg" },
      SS:      { display: "M. Fitzpatrick", initials: "MF", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 93, nameBold: true , headshot: "Fitzpatrick_Minkah.jpg" },
      FS:      { display: "D. Elliott", initials: "DE", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 , headshot: "Elliott_DeShon.jpg" },
      NB:      { display: "J. Ramsey", initials: "JR", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 87 , headshot: "Ramsey_Jalen.jpg" },
      OLB_L:   { display: "A. Highsmith", initials: "AH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 85 , headshot: "Highsmith_Alex.jpg" },
      ILB_L:   { display: "P. Queen", initials: "PQ", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 80 , headshot: "Queen_Patrick.jpg" },
      ILB_R:   { display: "C. Holcomb", initials: "CH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 , headshot: "Holcomb_Cole.jpg" },
      OLB_R:   { display: "T. Watt", initials: "TW", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 99, nameBold: true , headshot: "Watt_T.J..jpg" },
      DE_L:    { display: "C. Heyward", initials: "CH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 94, nameBold: true , headshot: "Heyward_Cameron.jpg" },
      NT:      { display: "M. Adams", initials: "MA", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 , headshot: "Adams_Montravius.jpg" },
      DE_R:    { display: "L. Ogunjobi", initials: "LO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 80 , headshot: "Ogunjobi_Larry.jpg" },
    },
  },
  matchupSummary: {
    grades: [
      {
        label: "Pass Protection",
        awayGrade: "C-",
        homeGrade: "A",
        note: "T.J. Watt (99) vs ATL's OLine — could wreck the game inside the first two drives, analysts say",
      },
      {
        label: "QB vs Pass Rush",
        awayGrade: "C-",
        homeGrade: "A",
        note: "M. Penix Jr. (72) vs T.J. Watt (99) — worst possible debut environment for Penix; Watt generates pressure every other snap",
      },
      {
        label: "RB in Space",
        awayGrade: "A",
        homeGrade: "C-",
        note: "B. Robinson (93) vs P. Queen (80) — RB in space and catching out of backfield",
      },
      {
        label: "TE Matchup",
        awayGrade: "A",
        homeGrade: "C-",
        note: "K. Pitts (84) creates mismatches vs P. Queen (80) — TE vs linebacker coverage",
      },
      {
        label: "Slot Matchup",
        awayGrade: "C-",
        homeGrade: "A",
        note: "K. Hodge (72) vs J. Ramsey (87) — slot matchup in the middle of the field",
      },
    ],
    verdict: "Watt (99) + Heyward (94) make life miserable for Penix on primetime debut — PIT covers at home",
  },
};
