import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "atl-pit",
  away: {
    name: "Atlanta Falcons",
    abbr: "ATL",
    color: "#A71930",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "D. London", initials: "DL", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 91, nameBold: true },
      LT:       { display: "J. Matthews", initials: "JM", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 82, maxWidth: 36 },
      LG:       { display: "M. Bergeron", initials: "MB", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 76, maxWidth: 36 },
      C:        { display: "D. Dalman", initials: "DD", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "C. Lindstrom", initials: "CL", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 94, maxWidth: 36, nameBold: true },
      RT:       { display: "K. McGary", initials: "KM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 79, maxWidth: 36 },
      TE:       { display: "K. Pitts", initials: "KP", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 84 },
      SLOT:     { display: "K. Hodge", initials: "KH", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 },
      WR_RIGHT: { display: "D. Mooney", initials: "DM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 80 },
      QB:       { display: "M. Penix Jr.", initials: "MP", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 72, nameBold: true },
      RB:       { display: "B. Robinson", initials: "BR", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 93, nameBold: true },
    },
    defense: {
      CB_LEFT: { display: "A. Terrell", initials: "AT", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 86 },
      SS:      { display: "J. Bates III", initials: "JB", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 88 },
      FS:      { display: "D. Hellams", initials: "DH", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 73 },
      NB:      { display: "J. Okudah", initials: "JO", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 },
      OLB_L:   { display: "A. Ebiketie", initials: "AE", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 },
      ILB_L:   { display: "K. Elliss", initials: "KE", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      ILB_R:   { display: "T. Andersen", initials: "TA", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 },
      OLB_R:   { display: "J. Pearce Jr.", initials: "JP", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 },
      DE_L:    { display: "T. Graham", initials: "TG", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
      NT:      { display: "D. Onyemata", initials: "DO", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 78 },
      DE_R:    { display: "R. Orhorhoro", initials: "RO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
    },
  },
  home: {
    name: "Pittsburgh Steelers",
    abbr: "PIT",
    color: "#FFB612",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 1 Zone Blitz",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "D. Metcalf", initials: "DM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 85 },
      LT:       { display: "D. Moore Jr.", initials: "DM", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 76, maxWidth: 36 },
      LG:       { display: "I. Seumalo", initials: "IS", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 83, maxWidth: 36 },
      C:        { display: "N. Herbig", initials: "NH", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 },
      RG:       { display: "J. Daniels", initials: "JD", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 80, maxWidth: 36 },
      RT:       { display: "B. Jones", initials: "BJ", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 78, maxWidth: 36 },
      TE:       { display: "P. Freiermuth", initials: "PF", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 80 },
      SLOT:     { display: "B. Skowronek", initials: "BS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 },
      WR_RIGHT: { display: "V. Jefferson", initials: "VJ", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 73 },
      QB:       { display: "A. Rodgers", initials: "AR", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 78, nameBold: true },
      RB:       { display: "N. Harris", initials: "NH", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 80 },
    },
    defense: {
      CB_LEFT: { display: "J. Porter Jr.", initials: "JP", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 80 },
      SS:      { display: "M. Fitzpatrick", initials: "MF", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 93, nameBold: true },
      FS:      { display: "D. Elliott", initials: "DE", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 },
      NB:      { display: "J. Ramsey", initials: "JR", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 87 },
      OLB_L:   { display: "A. Highsmith", initials: "AH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 85 },
      ILB_L:   { display: "P. Queen", initials: "PQ", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 80 },
      ILB_R:   { display: "C. Holcomb", initials: "CH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 },
      OLB_R:   { display: "T. Watt", initials: "TW", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 99, nameBold: true },
      DE_L:    { display: "C. Heyward", initials: "CH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 94, nameBold: true },
      NT:      { display: "M. Adams", initials: "MA", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 },
      DE_R:    { display: "L. Ogunjobi", initials: "LO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 80 },
    },
  },
};
