import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "bal-ind",
  away: {
    name: "Baltimore Ravens",
    abbr: "BAL",
    color: "#241773",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 2 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "Z. Flowers", initials: "ZF", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 },
      LT:       { display: "R. Stanley", initials: "RS", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 90, maxWidth: 36, nameBold: true },
      LG:       { display: "B. Cleveland", initials: "BC", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 78, maxWidth: 36 },
      C:        { display: "T. Linderbaum", initials: "TL", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 87, maxWidth: 36 },
      RG:       { display: "D. Faalele", initials: "DF", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 76, maxWidth: 36 },
      RT:       { display: "P. Mekari", initials: "PM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 76, maxWidth: 36 },
      TE:       { display: "M. Andrews", initials: "MA", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 91, nameBold: true },
      SLOT:     { display: "R. Bateman", initials: "RB", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 78 },
      WR_RIGHT: { display: "N. Agholor", initials: "NA", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 74 },
      QB:       { display: "L. Jackson", initials: "LJ", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 99, nameBold: true },
      RB:       { display: "D. Henry", initials: "DH", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 98, nameBold: true },
    },
    defense: {
      CB_LEFT: { display: "M. Humphrey", initials: "MH", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 92, nameBold: true },
      SS:      { display: "K. Hamilton", initials: "KH", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 91, nameBold: true },
      FS:      { display: "M. Williams", initials: "MW", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 80 },
      NB:      { display: "A. Maulet", initials: "AM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 72 },
      OLB_L:   { display: "D. Ojabo", initials: "DO", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 },
      ILB_L:   { display: "R. Smith", initials: "RS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 94, nameBold: true },
      ILB_R:   { display: "M. Harrison", initials: "MH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 },
      OLB_R:   { display: "T. Hendrickson", initials: "TH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 92, nameBold: true },
      DE_L:    { display: "B. Washington", initials: "BW", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 74 },
      NT:      { display: "N. Madubuike", initials: "NM", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 92, nameBold: true },
      DE_R:    { display: "T. Jones", initials: "TJ", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
    },
  },
  home: {
    name: "Indianapolis Colts",
    abbr: "IND",
    color: "#003A75",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "M. Pittman Jr.", initials: "MP", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 84 },
      LT:       { display: "B. Raimann", initials: "BR", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 80, maxWidth: 36 },
      LG:       { display: "Q. Nelson", initials: "QN", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 92, maxWidth: 36, nameBold: true },
      C:        { display: "W. French", initials: "WF", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 },
      RG:       { display: "W. Fries", initials: "WF", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 78, maxWidth: 36 },
      RT:       { display: "M. Goncalves", initials: "MG", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 74, maxWidth: 36 },
      TE:       { display: "M. Alie-Cox", initials: "MA", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 74 },
      SLOT:     { display: "A. Pierce", initials: "AP", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 76 },
      WR_RIGHT: { display: "J. Downs", initials: "JD", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 79 },
      QB:       { display: "D. Jones", initials: "DJ", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 72, nameBold: true },
      RB:       { display: "J. Taylor", initials: "JT", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 88 },
    },
    defense: {
      CB_LEFT: { display: "K. Moore II", initials: "KM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 80 },
      SS:      { display: "R. Thomas II", initials: "RT", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 78 },
      FS:      { display: "N. Cross", initials: "NC", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 78 },
      NB:      { display: "J. Blackmon", initials: "JB", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "K. Paye", initials: "KP", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 80 },
      ILB_L:   { display: "E. Speed", initials: "ES", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      ILB_R:   { display: "Z. Franklin", initials: "ZF", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 },
      OLB_R:   { display: "S. Ebukam", initials: "SE", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 },
      DE_L:    { display: "D. Buckner", initials: "DB", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 88 },
      NT:      { display: "G. Stewart", initials: "GS", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 82 },
      DE_R:    { display: "D. Odeyingbo", initials: "DO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
    },
  },
};
