import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "buf-hou",
  away: {
    name: "Buffalo Bills",
    abbr: "BUF",
    color: "#00338D",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 2 Zone",
    defScheme: "3-4 Base",
    defDescription: "Buffalo's 3-4 under Sean McDermott is disciplined two-gap football. Greg Rousseau (88 OVR) rushes from the SAM OLB spot while Ed Oliver (83 OVR) is the interior disruptor at 1-tech. Cover 2 zone emphasizes wide-side corner Taron Johnson in the nickel. Terrel Bernard commands the inside.",
    offense: {
      WR_LEFT:  { display: "D. Moore", initials: "DM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 85 , headshot: "Moore_DJ.jpg" },
      LT:       { display: "D. Dawkins", initials: "DD", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 91, maxWidth: 36, nameBold: true , headshot: "Dawkins_Dion.jpg" },
      LG:       { display: "D. Edwards", initials: "DE", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 78, maxWidth: 36 , headshot: "Edwards_David.jpg" },
      C:        { display: "C. McGovern", initials: "CM", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 78, maxWidth: 36 , headshot: "McGovern_Connor.jpg" },
      RG:       { display: "O. Torrence", initials: "OT", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 80, maxWidth: 36 , headshot: "Torrence_O'Cyrus.jpg" },
      RT:       { display: "S. Brown", initials: "SB", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 78, maxWidth: 36 , headshot: "Brown_Spencer.jpg" },
      TE:       { display: "D. Kincaid", initials: "DK", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 79 , headshot: "Kincaid_Dalton.jpg" },
      SLOT:     { display: "K. Shakir", initials: "KS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 82 , headshot: "Shakir_Khalil.jpg" },
      WR_RIGHT: { display: "K. Coleman", initials: "KC", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 78 , headshot: "Coleman_Keon.jpg" },
      QB:       { display: "J. Allen", initials: "JA", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 99, nameBold: true , headshot: "Allen_Josh.jpg" },
      RB:       { display: "J. Cook", initials: "JC", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 89 , headshot: "Cook_James.jpg" },
    },
    defense: {
      CB_LEFT: { display: "C. Benford", initials: "CB", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 85 , headshot: "Benford_Christian.jpg" },
      SS:      { display: "T. Rapp", initials: "TR", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 78 },
      FS:      { display: "D. Hamlin", initials: "DH", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 , headshot: "Hamlin_Damar.jpg" },
      NB:      { display: "T. Johnson", initials: "TJ", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 80 , headshot: "Johnson_Taron.jpg" },
      OLB_L:   { display: "G. Rousseau", initials: "GR", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 88 , headshot: "Rousseau_Greg.jpg" },
      ILB_L:   { display: "T. Bernard", initials: "TB", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 82 , headshot: "Bernard_Terrel.jpg" },
      ILB_R:   { display: "B. Spector", initials: "BS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 },
      OLB_R:   { display: "A. Epenesa", initials: "AE", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 79 , headshot: "Epenesa_AJ.jpg" },
      DE_L:    { display: "D. Jones", initials: "DJ", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 , headshot: "Jones_DaQuan.jpg" },
      NT:      { display: "E. Oliver", initials: "EO", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 83 , headshot: "Oliver_Ed.jpg" },
      DE_R:    { display: "D. Tomlinson", initials: "DT", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 80 , headshot: "Tomlinson_Dalvin.jpg" },
    },
  },
  home: {
    name: "Houston Texans",
    abbr: "HOU",
    color: "#03202F",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Houston's 4-3 features Will Anderson Jr. (91 OVR) and Danielle Hunter (91 OVR) as a terrifying bookend pass rush — one of the league's best. Derek Stingley Jr. (92 OVR) plays shadow coverage on the opponent's top receiver. Cover 3 zone with Jalen Pitre as an aggressive box safety.",
    offense: {
      WR_LEFT:  { display: "N. Collins", initials: "NC", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 , headshot: "Collins_Nico.jpg" },
      LT:       { display: "L. Tunsil", initials: "LT", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 94, maxWidth: 36, nameBold: true , headshot: "Tunsil_Laremy.jpg" },
      LG:       { display: "K. Green", initials: "KG", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 76, maxWidth: 36 , headshot: "Green_Kenyon.jpg" },
      C:        { display: "J. Scruggs", initials: "JS", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 , headshot: "Scruggs_Juice.jpg" },
      RG:       { display: "S. Mason", initials: "SM", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 82, maxWidth: 36 },
      RT:       { display: "B. Smith", initials: "BS", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 80, maxWidth: 36 , headshot: "Smith_Braden.jpg" },
      TE:       { display: "D. Schultz", initials: "DS", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 83 , headshot: "Schultz_Dalton.jpg" },
      SLOT:     { display: "J. Metchie III", initials: "JM", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 , headshot: "Metchie III_John.jpg" },
      WR_RIGHT: { display: "T. Dell", initials: "TD", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 78 , headshot: "Dell_Tank.jpg" },
      QB:       { display: "C. Stroud", initials: "CS", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 78, nameBold: true , headshot: "Stroud_CJ.jpg" },
      RB:       { display: "D. Montgomery", initials: "DM", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 81 , headshot: "Montgomery_David.jpg" },
    },
    defense: {
      CB_LEFT: { display: "D. Stingley Jr.", initials: "DS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 92, nameBold: true , headshot: "Stingley Jr._Derek.jpg" },
      SS:      { display: "J. Pitre", initials: "JP", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 84 , headshot: "Pitre_Jalen.jpg" },
      FS:      { display: "E. Murray", initials: "EM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 , headshot: "Murray_Eric.jpg" },
      NB:      { display: "J. Ward", initials: "JW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 , headshot: "Ward_Jimmie.jpg" },
      OLB_L:   { display: "W. Anderson Jr.", initials: "WA", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 91, nameBold: true , headshot: "Anderson Jr._Will.jpg" },
      ILB_L:   { display: "C. Harris", initials: "CH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 , headshot: "Harris_Christian.jpg" },
      ILB_R:   { display: "H. To'oTo'o", initials: "HT", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 , headshot: "To'oTo'o_Henry.jpg" },
      OLB_R:   { display: "D. Hunter", initials: "DH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 91, nameBold: true , headshot: "Hunter_Danielle.jpg" },
      DE_L:    { display: "S. Rankins", initials: "SR", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 , headshot: "Rankins_Sheldon.jpg" },
      NT:      { display: "F. Fatukasi", initials: "FF", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 76 },
      DE_R:    { display: "M. Edwards Jr.", initials: "ME", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 74 },
    },
  },
};
