import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "buf-hou",
  away: {
    name: "Buffalo Bills",
    abbr: "BUF",
    color: "#00338D",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 2 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "D. Moore", initials: "DM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 85 },
      LT:       { display: "D. Dawkins", initials: "DD", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 91, maxWidth: 36, nameBold: true },
      LG:       { display: "D. Edwards", initials: "DE", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 78, maxWidth: 36 },
      C:        { display: "C. McGovern", initials: "CM", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 78, maxWidth: 36 },
      RG:       { display: "O. Torrence", initials: "OT", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 80, maxWidth: 36 },
      RT:       { display: "S. Brown", initials: "SB", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 78, maxWidth: 36 },
      TE:       { display: "D. Kincaid", initials: "DK", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 79 },
      SLOT:     { display: "K. Shakir", initials: "KS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 82 },
      WR_RIGHT: { display: "K. Coleman", initials: "KC", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 78 },
      QB:       { display: "J. Allen", initials: "JA", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 99, nameBold: true },
      RB:       { display: "J. Cook", initials: "JC", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 89 },
    },
    defense: {
      CB_LEFT: { display: "C. Benford", initials: "CB", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 85 },
      SS:      { display: "T. Rapp", initials: "TR", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 78 },
      FS:      { display: "D. Hamlin", initials: "DH", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 },
      NB:      { display: "T. Johnson", initials: "TJ", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 80 },
      OLB_L:   { display: "G. Rousseau", initials: "GR", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 88 },
      ILB_L:   { display: "T. Bernard", initials: "TB", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 82 },
      ILB_R:   { display: "B. Spector", initials: "BS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 },
      OLB_R:   { display: "A. Epenesa", initials: "AE", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 79 },
      DE_L:    { display: "D. Jones", initials: "DJ", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 },
      NT:      { display: "E. Oliver", initials: "EO", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 83 },
      DE_R:    { display: "D. Tomlinson", initials: "DT", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 80 },
    },
  },
  home: {
    name: "Houston Texans",
    abbr: "HOU",
    color: "#03202F",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "N. Collins", initials: "NC", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 },
      LT:       { display: "L. Tunsil", initials: "LT", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 94, maxWidth: 36, nameBold: true },
      LG:       { display: "K. Green", initials: "KG", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 76, maxWidth: 36 },
      C:        { display: "J. Scruggs", initials: "JS", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "S. Mason", initials: "SM", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 82, maxWidth: 36 },
      RT:       { display: "B. Smith", initials: "BS", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 80, maxWidth: 36 },
      TE:       { display: "D. Schultz", initials: "DS", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 83 },
      SLOT:     { display: "J. Metchie III", initials: "JM", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "T. Dell", initials: "TD", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 78 },
      QB:       { display: "C. Stroud", initials: "CS", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 78, nameBold: true },
      RB:       { display: "D. Montgomery", initials: "DM", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 81 },
    },
    defense: {
      CB_LEFT: { display: "D. Stingley Jr.", initials: "DS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 92, nameBold: true },
      SS:      { display: "J. Pitre", initials: "JP", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 84 },
      FS:      { display: "E. Murray", initials: "EM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 },
      NB:      { display: "J. Ward", initials: "JW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 },
      OLB_L:   { display: "W. Anderson Jr.", initials: "WA", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 91, nameBold: true },
      ILB_L:   { display: "C. Harris", initials: "CH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 },
      ILB_R:   { display: "H. To'oTo'o", initials: "HT", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 },
      OLB_R:   { display: "D. Hunter", initials: "DH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 91, nameBold: true },
      DE_L:    { display: "S. Rankins", initials: "SR", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
      NT:      { display: "F. Fatukasi", initials: "FF", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 76 },
      DE_R:    { display: "M. Edwards Jr.", initials: "ME", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 74 },
    },
  },
};
