import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "chi-car",
  away: {
    name: "Chicago Bears",
    abbr: "CHI",
    color: "#0B162A",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Montez Sweat (90 OVR) is the engine of Chicago's 4-3 pass rush, capable of winning from either side. Jaylon Johnson (86 OVR) plays press-man on the boundary while the interior pairs Grady Jarrett and Gervon Dexter. Cover 3 zone with Tremaine Edmunds dropping to the hook-curl.",
    offense: {
      WR_LEFT:  { display: "R. Odunze", initials: "RO", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 80 , headshot: "Odunze_Rome.jpg" },
      LT:       { display: "B. Jones", initials: "BJ", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 76, maxWidth: 36 , headshot: "Jones_Braxton.jpg" },
      LG:       { display: "J. Thuney", initials: "JT", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 92, maxWidth: 36, nameBold: true , headshot: "Thuney_Joe.jpg" },
      C:        { display: "D. Kramer", initials: "DK", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 72, maxWidth: 36 , headshot: "Kramer_Doug.jpg" },
      RG:       { display: "N. Davis", initials: "ND", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 78, maxWidth: 36 , headshot: "Davis_Nate.jpg" },
      RT:       { display: "D. Wright", initials: "DW", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 82, maxWidth: 36 , headshot: "Wright_Darnell.jpg" },
      TE:       { display: "C. Kmet", initials: "CK", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 82 , headshot: "Kmet_Cole.jpg" },
      SLOT:     { display: "T. Scott", initials: "TS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 , headshot: "Scott_Tyler.jpg" },
      WR_RIGHT: { display: "L. Burden III", initials: "LB", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 76 , headshot: "Burden III_Luther.jpg" },
      QB:       { display: "C. Williams", initials: "CW", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true , headshot: "Williams_Caleb.jpg" },
      RB:       { display: "D. Swift", initials: "DS", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 80 , headshot: "Swift_D'Andre.jpg" },
    },
    defense: {
      CB_LEFT: { display: "J. Johnson", initials: "JJ", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 86 , headshot: "Johnson_Jaylon.jpg" },
      SS:      { display: "D. Thieneman", initials: "DT", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 74 , headshot: "Thieneman_Dillon.jpg" },
      FS:      { display: "C. Bryant", initials: "CB", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 , headshot: "Bryant_Coby.jpg" },
      NB:      { display: "T. Stevenson", initials: "TS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 , headshot: "Stevenson_Tyrique.jpg" },
      OLB_L:   { display: "M. Sweat", initials: "MS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 90, nameBold: true , headshot: "Sweat_Montez.jpg" },
      ILB_L:   { display: "T. Edmunds", initials: "TE", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 82 , headshot: "Edmunds_Tremaine.jpg" },
      ILB_R:   { display: "J. Sanborn", initials: "JS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 , headshot: "Sanborn_Jack.jpg" },
      OLB_R:   { display: "D. Walker", initials: "DW", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 , headshot: "Walker_DeMarcus.jpg" },
      DE_L:    { display: "G. Jarrett", initials: "GJ", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 80 , headshot: "Jarrett_Grady.jpg" },
      NT:      { display: "A. Billings", initials: "AB", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 74 , headshot: "Billings_Andrew.jpg" },
      DE_R:    { display: "G. Dexter", initials: "GD", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 , headshot: "Dexter_Gervon.jpg" },
    },
  },
  home: {
    name: "Carolina Panthers",
    abbr: "CAR",
    color: "#0085CA",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Carolina's 4-3 relies on Derrick Brown (82 OVR) as the disruptive DT and Jaycee Horn (84 OVR) as a physical press corner. Shaq Thompson and Josey Jewell man the inside linebackers in a Cover 3 zone scheme. Carolina generates most of its pressure via Myles Murphy off the edge.",
    offense: {
      WR_LEFT:  { display: "T. McMillan", initials: "TM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 82 , headshot: "McMillan_Tetairoa.jpg" },
      LT:       { display: "I. Ekwonu", initials: "IE", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 79, maxWidth: 36 , headshot: "Ekwonu_Ikem.jpg" },
      LG:       { display: "R. Hunt", initials: "RH", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 82, maxWidth: 36 , headshot: "Hunt_Robert.jpg" },
      C:        { display: "R. Hainsey", initials: "RH", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 73, maxWidth: 36 , headshot: "Hainsey_Robert.jpg" },
      RG:       { display: "D. Lewis", initials: "DL", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 76, maxWidth: 36 , headshot: "Lewis_Damien.jpg" },
      RT:       { display: "T. Moton", initials: "TM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 84, maxWidth: 36 , headshot: "Moton_Taylor.jpg" },
      TE:       { display: "T. Tremble", initials: "TT", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 72 , headshot: "Tremble_Tommy.jpg" },
      SLOT:     { display: "A. Thielen", initials: "AT", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "J. Coker", initials: "JC", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 73 , headshot: "Coker_Jalen.jpg" },
      QB:       { display: "B. Young", initials: "BY", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 77, nameBold: true , headshot: "Young_Bryce.jpg" },
      RB:       { display: "C. Hubbard", initials: "CH", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 78 , headshot: "Hubbard_Chuba.jpg" },
    },
    defense: {
      CB_LEFT: { display: "J. Horn", initials: "JH", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 84 , headshot: "Horn_Jaycee.jpg" },
      SS:      { display: "X. Woods", initials: "XW", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 76 , headshot: "Woods_Xavier.jpg" },
      FS:      { display: "S. Franklin Jr.", initials: "SF", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 70 , headshot: "Franklin Jr._Sam.jpg" },
      NB:      { display: "L. Johnson Jr.", initials: "LJ", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 72 , headshot: "Johnson Jr._Lonnie.jpg" },
      OLB_L:   { display: "E. Leota", initials: "EL", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 72 , headshot: "Leota_Eku.jpg" },
      ILB_L:   { display: "S. Thompson", initials: "ST", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 , headshot: "Thompson_Shaq.jpg" },
      ILB_R:   { display: "J. Jewell", initials: "JJ", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "Jewell_Josey.jpg" },
      OLB_R:   { display: "D. Johnson", initials: "DJ", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 , headshot: "Johnson_DJ.jpg" },
      DE_L:    { display: "M. Murphy", initials: "MM", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 , headshot: "Murphy_Myles.jpg" },
      NT:      { display: "D. Brown", initials: "DB", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 82 , headshot: "Brown_Derrick.jpg" },
      DE_R:    { display: "S. Tuttle", initials: "ST", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 73 , headshot: "Tuttle_Shy.jpg" },
    },
  },
};
