import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "chi-car",
  away: {
    name: "Chicago Bears",
    abbr: "CHI",
    color: "#0B162A",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "R. Odunze", initials: "RO", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 80 },
      LT:       { display: "B. Jones", initials: "BJ", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 76, maxWidth: 36 },
      LG:       { display: "J. Thuney", initials: "JT", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 92, maxWidth: 36, nameBold: true },
      C:        { display: "D. Kramer", initials: "DK", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 72, maxWidth: 36 },
      RG:       { display: "N. Davis", initials: "ND", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 78, maxWidth: 36 },
      RT:       { display: "D. Wright", initials: "DW", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 82, maxWidth: 36 },
      TE:       { display: "C. Kmet", initials: "CK", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 82 },
      SLOT:     { display: "T. Scott", initials: "TS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 },
      WR_RIGHT: { display: "L. Burden III", initials: "LB", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 76 },
      QB:       { display: "C. Williams", initials: "CW", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true },
      RB:       { display: "D. Swift", initials: "DS", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 80 },
    },
    defense: {
      CB_LEFT: { display: "J. Johnson", initials: "JJ", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 86 },
      SS:      { display: "D. Thieneman", initials: "DT", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 74 },
      FS:      { display: "C. Bryant", initials: "CB", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 },
      NB:      { display: "T. Stevenson", initials: "TS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "M. Sweat", initials: "MS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 90, nameBold: true },
      ILB_L:   { display: "T. Edmunds", initials: "TE", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 82 },
      ILB_R:   { display: "J. Sanborn", initials: "JS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 },
      OLB_R:   { display: "D. Walker", initials: "DW", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 },
      DE_L:    { display: "G. Jarrett", initials: "GJ", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 80 },
      NT:      { display: "A. Billings", initials: "AB", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 74 },
      DE_R:    { display: "G. Dexter", initials: "GD", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
    },
  },
  home: {
    name: "Carolina Panthers",
    abbr: "CAR",
    color: "#0085CA",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "T. McMillan", initials: "TM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 82 },
      LT:       { display: "I. Ekwonu", initials: "IE", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 79, maxWidth: 36 },
      LG:       { display: "R. Hunt", initials: "RH", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 82, maxWidth: 36 },
      C:        { display: "R. Hainsey", initials: "RH", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 73, maxWidth: 36 },
      RG:       { display: "D. Lewis", initials: "DL", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 76, maxWidth: 36 },
      RT:       { display: "T. Moton", initials: "TM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 84, maxWidth: 36 },
      TE:       { display: "T. Tremble", initials: "TT", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 72 },
      SLOT:     { display: "A. Thielen", initials: "AT", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "J. Coker", initials: "JC", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 73 },
      QB:       { display: "B. Young", initials: "BY", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 77, nameBold: true },
      RB:       { display: "C. Hubbard", initials: "CH", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 78 },
    },
    defense: {
      CB_LEFT: { display: "J. Horn", initials: "JH", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 84 },
      SS:      { display: "X. Woods", initials: "XW", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 76 },
      FS:      { display: "S. Franklin Jr.", initials: "SF", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 70 },
      NB:      { display: "L. Johnson Jr.", initials: "LJ", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 72 },
      OLB_L:   { display: "E. Leota", initials: "EL", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 72 },
      ILB_L:   { display: "S. Thompson", initials: "ST", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 },
      ILB_R:   { display: "J. Jewell", initials: "JJ", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      OLB_R:   { display: "D. Johnson", initials: "DJ", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 },
      DE_L:    { display: "M. Murphy", initials: "MM", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 },
      NT:      { display: "D. Brown", initials: "DB", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 82 },
      DE_R:    { display: "S. Tuttle", initials: "ST", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 73 },
    },
  },
};
