import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "cle-jax",
  away: {
    name: "Cleveland Browns",
    abbr: "CLE",
    color: "#311D00",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "J. Jeudy", initials: "JJ", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 82 },
      LT:       { display: "J. Wills Jr.", initials: "JW", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 79, maxWidth: 36 },
      LG:       { display: "J. Bitonio", initials: "JB", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 88, maxWidth: 36 },
      C:        { display: "E. Pocic", initials: "EP", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "W. Teller", initials: "WT", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 86, maxWidth: 36 },
      RT:       { display: "J. Conklin", initials: "JC", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 80, maxWidth: 36 },
      TE:       { display: "D. Njoku", initials: "DN", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 84 },
      SLOT:     { display: "D. Bell", initials: "DB", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "C. Tillman", initials: "CT", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 74 },
      QB:       { display: "J. Flacco", initials: "JF", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 73, nameBold: true },
      RB:       { display: "J. Ford", initials: "JF", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 74 },
    },
    defense: {
      CB_LEFT: { display: "D. Ward", initials: "DW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 93, nameBold: true },
      SS:      { display: "G. Delpit", initials: "GD", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 82 },
      FS:      { display: "J. Thornhill", initials: "JT", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 },
      NB:      { display: "M. Emerson Jr.", initials: "ME", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 },
      OLB_L:   { display: "M. Garrett", initials: "MG", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 99, nameBold: true },
      ILB_L:   { display: "J. Owusu-Koramoah", initials: "JO", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 84 },
      ILB_R:   { display: "S. Takitaki", initials: "ST", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 72 },
      OLB_R:   { display: "Z. Smith", initials: "ZS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 80 },
      DE_L:    { display: "M. Hurst II", initials: "MH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
      NT:      { display: "M. Hall Jr.", initials: "MH", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 },
      DE_R:    { display: "I. McGuire", initials: "IM", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
    },
  },
  home: {
    name: "Jacksonville Jaguars",
    abbr: "JAX",
    color: "#006778",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Zone Blitz",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "G. Davis", initials: "GD", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 80 },
      LT:       { display: "A. Harrison", initials: "AH", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 79, maxWidth: 36 },
      LG:       { display: "C. Van Lanen", initials: "CV", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 73, maxWidth: 36 },
      C:        { display: "M. Morse", initials: "MM", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 79, maxWidth: 36 },
      RG:       { display: "E. Cleveland", initials: "EC", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 80, maxWidth: 36 },
      RT:       { display: "W. Little", initials: "WL", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 76, maxWidth: 36 },
      TE:       { display: "B. Strange", initials: "BS", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 },
      SLOT:     { display: "T. Hunter", initials: "TH", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 84 },
      WR_RIGHT: { display: "B. Thomas Jr.", initials: "BT", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 84 },
      QB:       { display: "T. Lawrence", initials: "TL", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 80, nameBold: true },
      RB:       { display: "T. Etienne Jr.", initials: "TE", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 85 },
    },
    defense: {
      CB_LEFT: { display: "T. Campbell", initials: "TC", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 82 },
      SS:      { display: "A. Cisco", initials: "AC", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 80 },
      FS:      { display: "D. Savage", initials: "DS", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 },
      NB:      { display: "R. Darby", initials: "RD", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "J. Hines-Allen", initials: "JH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 90, nameBold: true },
      ILB_L:   { display: "F. Oluokun", initials: "FO", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 83 },
      ILB_R:   { display: "V. Miller", initials: "VM", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 },
      OLB_R:   { display: "T. Walker", initials: "TW", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 },
      DE_L:    { display: "D. Hamilton", initials: "DH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
      NT:      { display: "M. Smith", initials: "MS", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 75 },
      DE_R:    { display: "R. Robertson-Harris", initials: "RR", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 73 },
    },
  },
};
