import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "cle-jax",
  away: {
    name: "Cleveland Browns",
    abbr: "CLE",
    color: "#311D00",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Myles Garrett (99 OVR) is the best defensive player in football and Cleveland's entire defensive identity. Denzel Ward (93 OVR) shadows #1 receivers in press man. Jeremiah Owusu-Koramoah (84 OVR) is a sideline-to-sideline rangy ILB. The Browns run Cover 3 but will play man behind Garrett's pressure.",
    offense: {
      WR_LEFT:  { display: "J. Jeudy", initials: "JJ", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 82 , headshot: "Jeudy_Jerry.jpg" },
      LT:       { display: "J. Wills Jr.", initials: "JW", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 79, maxWidth: 36 , headshot: "Wills Jr._Jedrick.jpg" },
      LG:       { display: "J. Bitonio", initials: "JB", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 88, maxWidth: 36 },
      C:        { display: "E. Pocic", initials: "EP", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "W. Teller", initials: "WT", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 86, maxWidth: 36 , headshot: "Teller_Wyatt.jpg" },
      RT:       { display: "J. Conklin", initials: "JC", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 80, maxWidth: 36 , headshot: "Conklin_Jack.jpg" },
      TE:       { display: "D. Njoku", initials: "DN", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 84 , headshot: "Njoku_David.jpg" },
      SLOT:     { display: "D. Bell", initials: "DB", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 , headshot: "Bell_David.jpg" },
      WR_RIGHT: { display: "C. Tillman", initials: "CT", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 74 , headshot: "Tillman_Cedric.jpg" },
      QB:       { display: "J. Flacco", initials: "JF", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 73, nameBold: true , headshot: "Flacco_Joe.jpg" },
      RB:       { display: "J. Ford", initials: "JF", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 74 , headshot: "Ford_Jerome.jpg" },
    },
    defense: {
      CB_LEFT: { display: "D. Ward", initials: "DW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 93, nameBold: true , headshot: "Ward_Denzel.jpg" },
      SS:      { display: "G. Delpit", initials: "GD", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 82 , headshot: "Delpit_Grant.jpg" },
      FS:      { display: "J. Thornhill", initials: "JT", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 },
      NB:      { display: "M. Emerson Jr.", initials: "ME", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 , headshot: "Emerson Jr._Martin.jpg" },
      OLB_L:   { display: "M. Garrett", initials: "MG", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 99, nameBold: true , headshot: "Garrett_Myles.jpg" },
      ILB_L:   { display: "J. Owusu-Koramoah", initials: "JO", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 84 , headshot: "Owusu-Koramoah_Jeremiah.jpg" },
      ILB_R:   { display: "S. Takitaki", initials: "ST", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 72 },
      OLB_R:   { display: "Z. Smith", initials: "ZS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 80 , headshot: "Smith_Za'Darius.jpg" },
      DE_L:    { display: "M. Hurst II", initials: "MH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
      NT:      { display: "M. Hall Jr.", initials: "MH", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 , headshot: "Hall Jr._Mike.jpg" },
      DE_R:    { display: "I. McGuire", initials: "IM", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 , headshot: "McGuire_Isaiah.jpg" },
    },
  },
  home: {
    name: "Jacksonville Jaguars",
    abbr: "JAX",
    color: "#006778",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Zone Blitz",
    defScheme: "4-3 Base",
    defDescription: "Jacksonville's 4-3 zone blitz scheme confuses protections with multiple looks. Josh Hines-Allen (90 OVR) is a premier edge rusher off the left side. Foyesade Oluokun (83 OVR) is one of the more underrated ILBs in football, leading the league in tackles multiple seasons. Tyson Campbell (82 OVR) handles the boundary corner.",
    offense: {
      WR_LEFT:  { display: "G. Davis", initials: "GD", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 80 , headshot: "Davis_Gabe.jpg" },
      LT:       { display: "A. Harrison", initials: "AH", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 79, maxWidth: 36 , headshot: "Harrison_Anton.jpg" },
      LG:       { display: "C. Van Lanen", initials: "CV", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 73, maxWidth: 36 , headshot: "Van Lanen_Cole.jpg" },
      C:        { display: "M. Morse", initials: "MM", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 79, maxWidth: 36 },
      RG:       { display: "E. Cleveland", initials: "EC", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 80, maxWidth: 36 , headshot: "Cleveland_Ezra.jpg" },
      RT:       { display: "W. Little", initials: "WL", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 76, maxWidth: 36 , headshot: "Little_Walker.jpg" },
      TE:       { display: "B. Strange", initials: "BS", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 , headshot: "Strange_Brenton.jpg" },
      SLOT:     { display: "T. Hunter", initials: "TH", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 84 , headshot: "Hunter_Travis.jpg" },
      WR_RIGHT: { display: "B. Thomas Jr.", initials: "BT", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 84 , headshot: "Thomas Jr._Brian.jpg" },
      QB:       { display: "T. Lawrence", initials: "TL", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 80, nameBold: true , headshot: "Lawrence_Trevor.jpg" },
      RB:       { display: "T. Etienne Jr.", initials: "TE", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 85 , headshot: "Etienne Jr._Travis.jpg" },
    },
    defense: {
      CB_LEFT: { display: "T. Campbell", initials: "TC", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 82 , headshot: "Campbell_Tyson.jpg" },
      SS:      { display: "A. Cisco", initials: "AC", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 80 , headshot: "Cisco_Andre.jpg" },
      FS:      { display: "D. Savage", initials: "DS", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 , headshot: "Savage_Darnell.jpg" },
      NB:      { display: "R. Darby", initials: "RD", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "J. Hines-Allen", initials: "JH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 90, nameBold: true , headshot: "Hines-Allen_Josh.jpg" },
      ILB_L:   { display: "F. Oluokun", initials: "FO", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 83 , headshot: "Oluokun_Foyesade.jpg" },
      ILB_R:   { display: "V. Miller", initials: "VM", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 , headshot: "Miller_Ventrell.jpg" },
      OLB_R:   { display: "T. Walker", initials: "TW", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 , headshot: "Walker_Travon.jpg" },
      DE_L:    { display: "D. Hamilton", initials: "DH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 , headshot: "Hamilton_DaVon.jpg" },
      NT:      { display: "M. Smith", initials: "MS", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 75 , headshot: "Smith_Maason.jpg" },
      DE_R:    { display: "R. Robertson-Harris", initials: "RR", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 73 , headshot: "Robertson-Harris_Roy.jpg" },
    },
  },
};
