import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "dal-nyg",
  away: {
    name: "Dallas Cowboys",
    abbr: "DAL",
    color: "#003594",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "C. Lamb", initials: "CL", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 95, nameBold: true },
      LT:       { display: "T. Guyton", initials: "TG", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 73, maxWidth: 36 },
      LG:       { display: "T. Smith", initials: "TS", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 80, maxWidth: 36 },
      C:        { display: "C. Beebe", initials: "CB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 },
      RG:       { display: "T. Booker", initials: "TB", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 77, maxWidth: 36 },
      RT:       { display: "T. Steele", initials: "TS", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 73, maxWidth: 36 },
      TE:       { display: "J. Ferguson", initials: "JF", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 81 },
      SLOT:     { display: "J. Tolbert", initials: "JT", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 73 },
      WR_RIGHT: { display: "G. Pickens", initials: "GP", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 83 },
      QB:       { display: "D. Prescott", initials: "DP", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 84, nameBold: true },
      RB:       { display: "J. Williams", initials: "JW", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 78 },
    },
    defense: {
      CB_LEFT: { display: "D. Bland", initials: "DB", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 87 },
      SS:      { display: "J. Kearse", initials: "JK", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 76 },
      FS:      { display: "D. Wilson", initials: "DW", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 75 },
      NB:      { display: "J. Lewis", initials: "JL", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 },
      OLB_L:   { display: "D. Armstrong", initials: "DA", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 },
      ILB_L:   { display: "D. Ezeiruaku", initials: "DE", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      ILB_R:   { display: "D. Clark", initials: "DC", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 },
      OLB_R:   { display: "R. Gary", initials: "RG", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 82 },
      DE_L:    { display: "Q. Williams", initials: "QW", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 90, nameBold: true },
      NT:      { display: "K. Clark", initials: "KC", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 88 },
      DE_R:    { display: "M. Smith", initials: "MS", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 74 },
    },
  },
  home: {
    name: "New York Giants",
    abbr: "NYG",
    color: "#0B2265",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "M. Nabers", initials: "MN", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 },
      LT:       { display: "A. Thomas", initials: "AT", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 88, maxWidth: 36 },
      LG:       { display: "J. Runyan", initials: "JR", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 84, maxWidth: 36 },
      C:        { display: "J. Michael Schmitz", initials: "JS", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 72, maxWidth: 36 },
      RG:       { display: "F. Mauigoa", initials: "FM", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 70, maxWidth: 36 },
      RT:       { display: "J. Eluemunor", initials: "JE", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 80, maxWidth: 36 },
      TE:       { display: "I. Likely", initials: "IL", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 },
      SLOT:     { display: "D. Slayton", initials: "DS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "W. Robinson", initials: "WR", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 83 },
      QB:       { display: "J. Dart", initials: "JD", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 72, nameBold: true },
      RB:       { display: "T. Tracy Jr.", initials: "TT", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 79 },
    },
    defense: {
      CB_LEFT: { display: "P. Adebo", initials: "PA", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 78 },
      SS:      { display: "T. Nubin", initials: "TN", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 74 },
      FS:      { display: "C. Flott", initials: "CF", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 },
      NB:      { display: "N. McCloud", initials: "NM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 72 },
      OLB_L:   { display: "K. Thibodeaux", initials: "KT", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 },
      ILB_L:   { display: "B. Okereke", initials: "BO", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 },
      ILB_R:   { display: "A. Reese", initials: "AR", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 70 },
      OLB_R:   { display: "A. Carter", initials: "AC", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 81 },
      DE_L:    { display: "B. Burns", initials: "BB", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 89 },
      NT:      { display: "D. Lawrence", initials: "DL", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 97, nameBold: true },
      DE_R:    { display: "D. Davidson", initials: "DD", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
    },
  },
};
