import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "dal-nyg",
  away: {
    name: "Dallas Cowboys",
    abbr: "DAL",
    color: "#003594",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    defDescription: "Dallas' 3-4 features Quinnen Williams (90 OVR) as the premier interior disruptor — a 3-tech who can win one-on-one. Rashan Gary (82 OVR) provides edge pressure off the SAM OLB spot. DaRon Bland (87 OVR) is a ball-hawk corner. Cover 3 zone with Jayron Kearse as the box safety.",
    offense: {
      WR_LEFT:  { display: "C. Lamb", initials: "CL", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 95, nameBold: true , headshot: "Lamb_CeeDee.jpg" },
      LT:       { display: "T. Guyton", initials: "TG", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 73, maxWidth: 36 , headshot: "Guyton_Tyler.jpg" },
      LG:       { display: "T. Smith", initials: "TS", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 80, maxWidth: 36 , headshot: "Smith_Tyler.jpg" },
      C:        { display: "C. Beebe", initials: "CB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 , headshot: "Beebe_Cooper.jpg" },
      RG:       { display: "T. Booker", initials: "TB", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 77, maxWidth: 36 , headshot: "Booker_Tyler.jpg" },
      RT:       { display: "T. Steele", initials: "TS", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 73, maxWidth: 36 , headshot: "Steele_Terence.jpg" },
      TE:       { display: "J. Ferguson", initials: "JF", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 81 , headshot: "Ferguson_Jake.jpg" },
      SLOT:     { display: "J. Tolbert", initials: "JT", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 73 , headshot: "Tolbert_Jalen.jpg" },
      WR_RIGHT: { display: "G. Pickens", initials: "GP", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 83 , headshot: "Pickens_George.jpg" },
      QB:       { display: "D. Prescott", initials: "DP", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 84, nameBold: true , headshot: "Prescott_Dak.jpg" },
      RB:       { display: "J. Williams", initials: "JW", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 78 , headshot: "Williams_Javonte.jpg" },
    },
    defense: {
      CB_LEFT: { display: "D. Bland", initials: "DB", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 87 , headshot: "Bland_DaRon.jpg" },
      SS:      { display: "J. Kearse", initials: "JK", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 76 , headshot: "Kearse_Jayron.jpg" },
      FS:      { display: "D. Wilson", initials: "DW", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 75 , headshot: "Wilson_Donovan.jpg" },
      NB:      { display: "J. Lewis", initials: "JL", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 , headshot: "Lewis_Jourdan.jpg" },
      OLB_L:   { display: "D. Armstrong", initials: "DA", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 , headshot: "Armstrong_Dorance.jpg" },
      ILB_L:   { display: "D. Ezeiruaku", initials: "DE", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "Ezeiruaku_Donovan.jpg" },
      ILB_R:   { display: "D. Clark", initials: "DC", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 , headshot: "Clark_Damone.jpg" },
      OLB_R:   { display: "R. Gary", initials: "RG", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 82 , headshot: "Gary_Rashan.jpg" },
      DE_L:    { display: "Q. Williams", initials: "QW", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 90, nameBold: true , headshot: "Williams_Quinnen.jpg" },
      NT:      { display: "K. Clark", initials: "KC", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 88 , headshot: "Clark_Kenny.jpg" },
      DE_R:    { display: "M. Smith", initials: "MS", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 74 , headshot: "Smith_Mazi.jpg" },
    },
  },
  home: {
    name: "New York Giants",
    abbr: "NYG",
    color: "#0B2265",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    defDescription: "New York's 3-4 rebuilt around Dexter Lawrence (97 OVR) — the best NT in football who is virtually unblockable at the point of attack. Abdul Carter is the explosive edge prospect who disrupts as a rookie OLB. Brian Burns (89 OVR) rounds out a formidable front. Kayvon Thibodeaux provides contain. Cover 3 zone with safeties Tyler Nubin and Cordale Flott.",
    offense: {
      WR_LEFT:  { display: "M. Nabers", initials: "MN", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 , headshot: "Nabers_Malik.jpg" },
      LT:       { display: "A. Thomas", initials: "AT", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 88, maxWidth: 36 , headshot: "Thomas_Andrew.jpg" },
      LG:       { display: "J. Runyan", initials: "JR", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 84, maxWidth: 36 , headshot: "Runyan_Jon.jpg" },
      C:        { display: "J. Michael Schmitz", initials: "JS", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 72, maxWidth: 36 , headshot: "Michael Schmitz_John.jpg" },
      RG:       { display: "F. Mauigoa", initials: "FM", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 70, maxWidth: 36 , headshot: "Mauigoa_Francis.jpg" },
      RT:       { display: "J. Eluemunor", initials: "JE", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 80, maxWidth: 36 , headshot: "Eluemunor_Jermaine.jpg" },
      TE:       { display: "I. Likely", initials: "IL", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 , headshot: "Likely_Isaiah.jpg" },
      SLOT:     { display: "D. Slayton", initials: "DS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 , headshot: "Slayton_Darius.jpg" },
      WR_RIGHT: { display: "W. Robinson", initials: "WR", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 83 , headshot: "Robinson_Wan'Dale.jpg" },
      QB:       { display: "J. Dart", initials: "JD", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 72, nameBold: true , headshot: "Dart_Jaxson.jpg" },
      RB:       { display: "T. Tracy Jr.", initials: "TT", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 79 , headshot: "Tracy Jr._Tyrone.jpg" },
    },
    defense: {
      CB_LEFT: { display: "P. Adebo", initials: "PA", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 78 , headshot: "Adebo_Paulson.jpg" },
      SS:      { display: "T. Nubin", initials: "TN", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 74 , headshot: "Nubin_Tyler.jpg" },
      FS:      { display: "C. Flott", initials: "CF", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 , headshot: "Flott_Cordale.jpg" },
      NB:      { display: "N. McCloud", initials: "NM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 72 , headshot: "McCloud_Nick.jpg" },
      OLB_L:   { display: "K. Thibodeaux", initials: "KT", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 , headshot: "Thibodeaux_Kayvon.jpg" },
      ILB_L:   { display: "B. Okereke", initials: "BO", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 , headshot: "Okereke_Bobby.jpg" },
      ILB_R:   { display: "A. Reese", initials: "AR", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 70 , headshot: "Reese_Arvell.jpg" },
      OLB_R:   { display: "A. Carter", initials: "AC", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 81 , headshot: "Carter_Abdul.jpg" },
      DE_L:    { display: "B. Burns", initials: "BB", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 89 , headshot: "Burns_Brian.jpg" },
      NT:      { display: "D. Lawrence", initials: "DL", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 97, nameBold: true , headshot: "Lawrence_Dexter.jpg" },
      DE_R:    { display: "D. Davidson", initials: "DD", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 , headshot: "Davidson_D.J..jpg" },
    },
  },
};
