import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "den-kc",
  away: {
    name: "Denver Broncos",
    abbr: "DEN",
    color: "#FB4F14",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "C. Sutton", initials: "CS", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 85 },
      LT:       { display: "G. Bolles", initials: "GB", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 89, maxWidth: 36 },
      LG:       { display: "B. Powers", initials: "BP", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 76, maxWidth: 36 },
      C:        { display: "L. Wattenberg", initials: "LW", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 },
      RG:       { display: "Q. Meinerz", initials: "QM", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 95, maxWidth: 36, nameBold: true },
      RT:       { display: "M. McGlinchey", initials: "MM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 82, maxWidth: 36 },
      TE:       { display: "E. Engram", initials: "EE", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 85 },
      SLOT:     { display: "M. Mims Jr.", initials: "MM", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 80 },
      WR_RIGHT: { display: "J. Waddle", initials: "JW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 },
      QB:       { display: "B. Nix", initials: "BN", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 78, nameBold: true },
      RB:       { display: "J. McLaughlin", initials: "JM", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 73 },
    },
    defense: {
      CB_LEFT: { display: "P. Surtain II", initials: "PS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 97, nameBold: true },
      SS:      { display: "T. Hufanga", initials: "TH", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 86 },
      FS:      { display: "B. Jones", initials: "BJ", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 },
      NB:      { display: "J. Barron", initials: "JB", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 75 },
      OLB_L:   { display: "N. Bonitto", initials: "NB", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 91, nameBold: true },
      ILB_L:   { display: "A. Singleton", initials: "AS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      ILB_R:   { display: "D. Sanders", initials: "DS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 },
      OLB_R:   { display: "J. Cooper", initials: "JC", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 80 },
      DE_L:    { display: "D. Jones", initials: "DJ", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 79 },
      NT:      { display: "Z. Allen", initials: "ZA", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 87 },
      DE_R:    { display: "M. Henningsen", initials: "MH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
    },
  },
  home: {
    name: "Kansas City Chiefs",
    abbr: "KC",
    color: "#E31837",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-2-5 Nickel — Cover 1 Man",
    defScheme: "4-2-5 Nickel",
    offense: {
      WR_LEFT:  { display: "R. Rice", initials: "RR", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 84 },
      LT:       { display: "J. Simmons", initials: "JS", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 75, maxWidth: 36 },
      LG:       { display: "K. Suamataia", initials: "KS", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 75, maxWidth: 36 },
      C:        { display: "C. Humphrey", initials: "CH", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 94, maxWidth: 36, nameBold: true },
      RG:       { display: "T. Smith", initials: "TS", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 91, maxWidth: 36, nameBold: true },
      RT:       { display: "J. Taylor", initials: "JT", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 84, maxWidth: 36 },
      TE:       { display: "T. Kelce", initials: "TK", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 93, nameBold: true },
      SLOT:     { display: "X. Worthy", initials: "XW", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 80 },
      WR_RIGHT: { display: "H. Brown", initials: "HB", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 80 },
      QB:       { display: "P. Mahomes", initials: "PM", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 95, nameBold: true },
      RB:       { display: "I. Pacheco", initials: "IP", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 83 },
    },
    defense: {
      CB_LEFT: { display: "T. McDuffie", initials: "TM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 90, nameBold: true },
      SS:      { display: "J. Reid", initials: "JR", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 80 },
      FS:      { display: "B. Cook", initials: "BC", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 80 },
      NB:      { display: "N. Williams", initials: "NW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 73 },
      OLB_L:   { display: "F. Anudike-Uzomah", initials: "FA", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 },
      ILB_L:   { display: "N. Bolton", initials: "NB", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 83 },
      ILB_R:   { display: "L. Chenal", initials: "LC", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      OLB_R:   { display: "G. Karlaftis", initials: "GK", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 82 },
      DE_L:    { display: "M. Danna", initials: "MD", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
      NT:      { display: "C. Jones", initials: "CJ", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 97, nameBold: true },
      DE_R:    { display: "C. Omenihu", initials: "CO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
    },
  },
};
