import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "den-kc",
  away: {
    name: "Denver Broncos",
    abbr: "DEN",
    color: "#FB4F14",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    defDescription: "Denver's 3-4 is headlined by Pat Surtain II (97 OVR) — arguably the best corner in football, taking away an entire half of the field. Nik Bonitto (91 OVR) is a high-motor edge rusher off the left side. Zach Allen (87 OVR) anchors the interior. Talanoa Hufanga (86 OVR) is the single-high safety. Cover 3 zone with Surtain in press on the opponent's top WR.",
    offense: {
      WR_LEFT:  { display: "C. Sutton", initials: "CS", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 85 , headshot: "Sutton_Courtland.jpg" },
      LT:       { display: "G. Bolles", initials: "GB", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 89, maxWidth: 36 , headshot: "Bolles_Garett.jpg" },
      LG:       { display: "B. Powers", initials: "BP", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 76, maxWidth: 36 , headshot: "Powers_Ben.jpg" },
      C:        { display: "L. Wattenberg", initials: "LW", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 , headshot: "Wattenberg_Luke.jpg" },
      RG:       { display: "Q. Meinerz", initials: "QM", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 95, maxWidth: 36, nameBold: true , headshot: "Meinerz_Quinn.jpg" },
      RT:       { display: "M. McGlinchey", initials: "MM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 82, maxWidth: 36 , headshot: "McGlinchey_Mike.jpg" },
      TE:       { display: "E. Engram", initials: "EE", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 85 , headshot: "Engram_Evan.jpg" },
      SLOT:     { display: "M. Mims Jr.", initials: "MM", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 80 , headshot: "Mims Jr._Marvin.jpg" },
      WR_RIGHT: { display: "J. Waddle", initials: "JW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 , headshot: "Waddle_Jaylen.jpg" },
      QB:       { display: "B. Nix", initials: "BN", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 78, nameBold: true , headshot: "Nix_Bo.jpg" },
      RB:       { display: "J. McLaughlin", initials: "JM", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 73 , headshot: "McLaughlin_Jaleel.jpg" },
    },
    defense: {
      CB_LEFT: { display: "P. Surtain II", initials: "PS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 97, nameBold: true , headshot: "Surtain II_Pat.jpg" },
      SS:      { display: "T. Hufanga", initials: "TH", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 86 , headshot: "Hufanga_Talanoa.jpg" },
      FS:      { display: "B. Jones", initials: "BJ", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 , headshot: "Jones_Brandon.jpg" },
      NB:      { display: "J. Barron", initials: "JB", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 75 , headshot: "Barron_Jahdae.jpg" },
      OLB_L:   { display: "N. Bonitto", initials: "NB", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 91, nameBold: true , headshot: "Bonitto_Nik.jpg" },
      ILB_L:   { display: "A. Singleton", initials: "AS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "Singleton_Alex.jpg" },
      ILB_R:   { display: "D. Sanders", initials: "DS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 , headshot: "Sanders_Drew.jpg" },
      OLB_R:   { display: "J. Cooper", initials: "JC", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 80 , headshot: "Cooper_Jonathon.jpg" },
      DE_L:    { display: "D. Jones", initials: "DJ", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 79 , headshot: "Jones_D.J..jpg" },
      NT:      { display: "Z. Allen", initials: "ZA", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 87 , headshot: "Allen_Zach.jpg" },
      DE_R:    { display: "M. Henningsen", initials: "MH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 , headshot: "Henningsen_Matt.jpg" },
    },
  },
  home: {
    name: "Kansas City Chiefs",
    abbr: "KC",
    color: "#E31837",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-2-5 Nickel — Cover 1 Man",
    defScheme: "4-2-5 Nickel",
    defDescription: "Kansas City's 4-2-5 nickel plays physical Cover 1 man, leaning on Chris Jones (97 OVR) as an unblockable interior force. Trent McDuffie (90 OVR) shadows receivers in press. George Karlaftis (82 OVR) and Felix Anudike-Uzomah provide edge pressure. Nick Bolton (83 OVR) is the quarterback of the defense. Aggressive, physical, championship-tested.",
    offense: {
      WR_LEFT:  { display: "R. Rice", initials: "RR", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 84 , headshot: "Rice_Rashee.jpg" },
      LT:       { display: "J. Simmons", initials: "JS", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 75, maxWidth: 36 , headshot: "Simmons_Josh.jpg" },
      LG:       { display: "K. Suamataia", initials: "KS", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 75, maxWidth: 36 , headshot: "Suamataia_Kingsley.jpg" },
      C:        { display: "C. Humphrey", initials: "CH", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 94, maxWidth: 36, nameBold: true , headshot: "Humphrey_Creed.jpg" },
      RG:       { display: "T. Smith", initials: "TS", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 91, maxWidth: 36, nameBold: true , headshot: "Smith_Trey.jpg" },
      RT:       { display: "J. Taylor", initials: "JT", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 84, maxWidth: 36 , headshot: "Taylor_Jawaan.jpg" },
      TE:       { display: "T. Kelce", initials: "TK", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 93, nameBold: true , headshot: "Kelce_Travis.jpg" },
      SLOT:     { display: "X. Worthy", initials: "XW", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 80 , headshot: "Worthy_Xavier.jpg" },
      WR_RIGHT: { display: "H. Brown", initials: "HB", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 80 , headshot: "Brown_Hollywood.jpg" },
      QB:       { display: "P. Mahomes", initials: "PM", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 95, nameBold: true , headshot: "Mahomes_Patrick.jpg" },
      RB:       { display: "I. Pacheco", initials: "IP", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 83 , headshot: "Pacheco_Isiah.jpg" },
    },
    defense: {
      CB_LEFT: { display: "T. McDuffie", initials: "TM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 90, nameBold: true , headshot: "McDuffie_Trent.jpg" },
      SS:      { display: "J. Reid", initials: "JR", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 80 , headshot: "Reid_Justin.jpg" },
      FS:      { display: "B. Cook", initials: "BC", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 80 , headshot: "Cook_Bryan.jpg" },
      NB:      { display: "N. Williams", initials: "NW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 73 , headshot: "Williams_Nohl.jpg" },
      OLB_L:   { display: "F. Anudike-Uzomah", initials: "FA", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 , headshot: "Anudike-Uzomah_Felix.jpg" },
      ILB_L:   { display: "N. Bolton", initials: "NB", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 83 , headshot: "Bolton_Nick.jpg" },
      ILB_R:   { display: "L. Chenal", initials: "LC", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "Chenal_Leo.jpg" },
      OLB_R:   { display: "G. Karlaftis", initials: "GK", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 82 , headshot: "Karlaftis_George.jpg" },
      DE_L:    { display: "M. Danna", initials: "MD", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 , headshot: "Danna_Mike.jpg" },
      NT:      { display: "C. Jones", initials: "CJ", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 97, nameBold: true , headshot: "Jones_Chris.jpg" },
      DE_R:    { display: "C. Omenihu", initials: "CO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 , headshot: "Omenihu_Charles.jpg" },
    },
  },
};
