import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "gb-min",
  away: {
    name: "Green Bay Packers",
    abbr: "GB",
    color: "#203731",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "C. Watson", initials: "CW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 81 },
      LT:       { display: "D. Bakhtiari", initials: "DB", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 88, maxWidth: 36 },
      LG:       { display: "E. Jenkins", initials: "EJ", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 84, maxWidth: 36 },
      C:        { display: "J. Myers", initials: "JM", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "Z. Tom", initials: "ZT", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 87, maxWidth: 36 },
      RT:       { display: "Y. Nijman", initials: "YN", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 76, maxWidth: 36 },
      TE:       { display: "T. Kraft", initials: "TK", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 79 },
      SLOT:     { display: "J. Reed", initials: "JR", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 81 },
      WR_RIGHT: { display: "R. Doubs", initials: "RD", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 78 },
      QB:       { display: "J. Love", initials: "JL", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 83, nameBold: true },
      RB:       { display: "J. Jacobs", initials: "JJ", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 90, nameBold: true },
    },
    defense: {
      CB_LEFT: { display: "J. Alexander", initials: "JA", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 90, nameBold: true },
      SS:      { display: "D. Savage", initials: "DS", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 76 },
      FS:      { display: "T. Moore", initials: "TM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 72 },
      NB:      { display: "K. Nixon", initials: "KN", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 78 },
      OLB_L:   { display: "R. Gary", initials: "RG", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 86 },
      ILB_L:   { display: "D. Campbell", initials: "DC", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 80 },
      ILB_R:   { display: "I. McDuffie", initials: "IM", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 },
      OLB_R:   { display: "P. Smith", initials: "PS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 },
      DE_L:    { display: "D. Wyatt", initials: "DW", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 },
      NT:      { display: "K. Clark", initials: "KC", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 88 },
      DE_R:    { display: "J. Reed", initials: "JR", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 },
    },
  },
  home: {
    name: "Minnesota Vikings",
    abbr: "MIN",
    color: "#4F2683",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 2 Zone Blitz",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "J. Jefferson", initials: "JJ", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 99, nameBold: true },
      LT:       { display: "C. Darrisaw", initials: "CD", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 92, maxWidth: 36, nameBold: true },
      LG:       { display: "E. Cleveland", initials: "EC", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 80, maxWidth: 36 },
      C:        { display: "G. Bradbury", initials: "GB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "B. Brandel", initials: "BB", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 74, maxWidth: 36 },
      RT:       { display: "B. O'Neill", initials: "BO", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 84, maxWidth: 36 },
      TE:       { display: "T. Hockenson", initials: "TH", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 88 },
      SLOT:     { display: "J. Nailor", initials: "JN", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "J. Addison", initials: "JA", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 84 },
      QB:       { display: "J. McCarthy", initials: "JM", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 74, nameBold: true },
      RB:       { display: "A. Jones", initials: "AJ", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 80 },
    },
    defense: {
      CB_LEFT: { display: "S. Gilmore", initials: "SG", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 78 },
      SS:      { display: "H. Smith", initials: "HS", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 88 },
      FS:      { display: "J. Metellus", initials: "JM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 73 },
      NB:      { display: "M. Blackmon", initials: "MB", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 73 },
      OLB_L:   { display: "D. Turner", initials: "DT", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 },
      ILB_L:   { display: "J. Hicks", initials: "JH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      ILB_R:   { display: "B. Cashman", initials: "BC", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 },
      OLB_R:   { display: "A. Van Ginkel", initials: "AV", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 82 },
      DE_L:    { display: "H. Phillips", initials: "HP", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 },
      NT:      { display: "J. Allen", initials: "JA", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 88 },
      DE_R:    { display: "D. Lowry", initials: "DL", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 75 },
    },
  },
};
