import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "mia-lv",
  away: {
    name: "Miami Dolphins",
    abbr: "MIA",
    color: "#008E97",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Zone Blitz",
    defScheme: "3-4 Base",
    defDescription: "Miami's 3-4 zone blitz scheme under Anthony Weaver generates confusion with multiple disguised pressures. Christian Wilkins (86 OVR) and Zach Sieler (83 OVR) form a dominant interior. Bradley Chubb (84 OVR) leads the edge rush. Jevon Holland (82 OVR) is a versatile box safety. Xavien Howard (84 OVR) handles the boundary corner in press.",
    offense: {
      WR_LEFT:  { display: "T. Hill", initials: "TH", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 96, nameBold: true , headshot: "Hill_Tyreek.jpg" },
      LT:       { display: "T. Armstead", initials: "TA", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 88, maxWidth: 36 , headshot: "Armstead_Terron.jpg" },
      LG:       { display: "L. Eichenberg", initials: "LE", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 74, maxWidth: 36 , headshot: "Eichenberg_Liam.jpg" },
      C:        { display: "A. Brewer", initials: "AB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 , headshot: "Brewer_Aaron.jpg" },
      RG:       { display: "R. Jones", initials: "RJ", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 73, maxWidth: 36 , headshot: "Jones_Robert.jpg" },
      RT:       { display: "A. Jackson", initials: "AJ", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 76, maxWidth: 36 , headshot: "Jackson_Austin.jpg" },
      TE:       { display: "D. Smythe", initials: "DS", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 73 , headshot: "Smythe_Durham.jpg" },
      SLOT:     { display: "R. Cracraft", initials: "RC", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 , headshot: "Cracraft_River.jpg" },
      WR_RIGHT: { display: "B. Berrios", initials: "BB", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 72 , headshot: "Berrios_Braxton.jpg" },
      QB:       { display: "M. Willis", initials: "MW", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 74, nameBold: true , headshot: "Willis_Malik.jpg" },
      RB:       { display: "D. Achane", initials: "DA", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 83 , headshot: "Achane_De'Von.jpg" },
    },
    defense: {
      CB_LEFT: { display: "X. Howard", initials: "XH", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 84 , headshot: "Howard_Xavien.jpg" },
      SS:      { display: "J. Holland", initials: "JH", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 82 , headshot: "Holland_Jevon.jpg" },
      FS:      { display: "B. Jones", initials: "BJ", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 , headshot: "Jones_Brandon.jpg" },
      NB:      { display: "K. Kohou", initials: "KK", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 , headshot: "Kohou_Kader.jpg" },
      OLB_L:   { display: "B. Chubb", initials: "BC", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 84 , headshot: "Chubb_Bradley.jpg" },
      ILB_L:   { display: "D. Long Jr.", initials: "DL", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "Long Jr._David.jpg" },
      ILB_R:   { display: "J. Brooks", initials: "JB", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 77 , headshot: "Brooks_Jordyn.jpg" },
      OLB_R:   { display: "S. Barrett", initials: "SB", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 , headshot: "Barrett_Shaquil.jpg" },
      DE_L:    { display: "C. Wilkins", initials: "CW", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 86 , headshot: "Wilkins_Christian.jpg" },
      NT:      { display: "Z. Sieler", initials: "ZS", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 83 , headshot: "Sieler_Zach.jpg" },
      DE_R:    { display: "E. Ogbah", initials: "EO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 79 , headshot: "Ogbah_Emmanuel.jpg" },
    },
  },
  home: {
    name: "Las Vegas Raiders",
    abbr: "LV",
    color: "#000000",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Las Vegas' 4-3 lives and dies with Maxx Crosby (97 OVR) — a generational pass rusher who demands a chip or double team every snap. Behind Crosby, the Raiders' defensive depth is thin. Cover 3 zone with Nate Hobbs in the slot. The scheme is straightforward: get Crosby home and hope for turnovers.",
    offense: {
      WR_LEFT:  { display: "J. Meyers", initials: "JM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 78 , headshot: "Meyers_Jakobi.jpg" },
      LT:       { display: "K. Miller", initials: "KM", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 91, maxWidth: 36, nameBold: true , headshot: "Miller_Kolton.jpg" },
      LG:       { display: "D. Parham", initials: "DP", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 74, maxWidth: 36 , headshot: "Parham_Dylan.jpg" },
      C:        { display: "A. James", initials: "AJ", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 , headshot: "James_Andre.jpg" },
      RG:       { display: "T. Munford", initials: "TM", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 73, maxWidth: 36 , headshot: "Munford_Thayer.jpg" },
      RT:       { display: "A. Leatherwood", initials: "AL", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 72, maxWidth: 36 , headshot: "Leatherwood_Alex.jpg" },
      TE:       { display: "B. Bowers", initials: "BB", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 93, nameBold: true , headshot: "Bowers_Brock.jpg" },
      SLOT:     { display: "M. Gallup", initials: "MG", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 , headshot: "Gallup_Michael.jpg" },
      WR_RIGHT: { display: "D. Turner", initials: "DT", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 72 , headshot: "Turner_DJ.jpg" },
      QB:       { display: "A. O'Connell", initials: "AO", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 70, nameBold: true , headshot: "O'Connell_Aidan.jpg" },
      RB:       { display: "A. Mattison", initials: "AM", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 73 , headshot: "Mattison_Alexander.jpg" },
    },
    defense: {
      CB_LEFT: { display: "N. Hobbs", initials: "NH", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 , headshot: "Hobbs_Nate.jpg" },
      SS:      { display: "I. Pola-Mao", initials: "IP", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 72 , headshot: "Pola-Mao_Isaiah.jpg" },
      FS:      { display: "R. Teamer", initials: "RT", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 72 , headshot: "Teamer_Roderic.jpg" },
      NB:      { display: "B. Facyson", initials: "BF", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 71 , headshot: "Facyson_Brandon.jpg" },
      OLB_L:   { display: "M. Crosby", initials: "MC", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 97, nameBold: true , headshot: "Crosby_Maxx.jpg" },
      ILB_L:   { display: "A. Burney", initials: "AB", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 72 , headshot: "Burney_Amari.jpg" },
      ILB_R:   { display: "D. Deablo", initials: "DD", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 , headshot: "Deablo_Divine.jpg" },
      OLB_R:   { display: "M. Koonce", initials: "MK", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 , headshot: "Koonce_Malcolm.jpg" },
      DE_L:    { display: "J. Tillery", initials: "JT", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 74 , headshot: "Tillery_Jerry.jpg" },
      NT:      { display: "A. Butler", initials: "AB", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 , headshot: "Butler_Adam.jpg" },
      DE_R:    { display: "C. Snowden", initials: "CS", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 70 , headshot: "Snowden_Charles.jpg" },
    },
  },
  matchupSummary: {
    grades: [
      {
        label: "Pass Protection",
        awayGrade: "C-",
        homeGrade: "A",
        note: "T. Armstead (88) anchors pass pro vs M. Crosby (97) — edge pressure matchup",
      },
      {
        label: "WR vs Secondary",
        awayGrade: "A",
        homeGrade: "C-",
        note: "T. Hill (96) vs N. Hobbs (74) — receiving corps tests the opposing secondary",
      },
      {
        label: "QB vs Pass Rush",
        awayGrade: "C-",
        homeGrade: "A",
        note: "M. Willis (74) vs M. Crosby (97) — QB faces elite edge pressure",
      },
      {
        label: "WR1 vs CB1",
        awayGrade: "A",
        homeGrade: "C-",
        note: "T. Hill (96) vs N. Hobbs (74) — most glaring individual mismatch of Week 1; Hill runs free and MIA builds an early lead",
      },
      {
        label: "TE Matchup",
        awayGrade: "C-",
        homeGrade: "A",
        note: "B. Bowers (93) vs MIA's LBs — too fast for second-level defenders; analysts say 100+ yards is a realistic over/under",
      },
    ],
    verdict: "Hill runs free early; Crosby vs Armstead is LV's only hope — MIA wins, LV covers",
  },
};
