import type { GameMatchupData } from "@/lib/matchup-types";

export const NE_SEA: GameMatchupData = {
  id: "ne-sea-2026-w1",

  // ── NE — away ──────────────────────────────────────────────────────────────
  away: {
    name: "PATRIOTS",
    abbr: "NE",
    color: "#C8102E",
    logo: "/headshots/logo_ne.png",
    formation: "Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base",
    defScheme: "4-3 Base",
    defDescription: "New England's base 4-3 applies heavy press coverage with Christian Gonzalez (98 OVR) shadowing the opponent's top receiver. Robert Spillane anchors the linebacker corps. Four-man rush relies on Christian Barmore and Harold Landry III to generate pressure without blitzing.",
    offense: {
      WR_LEFT:  { display: "A.J. Brown",     initials: "AB", ringType: "wr", badgeType: "wr",   badgeLabel: "WR",       headshot: "Brown_A.J..jpg",           rating: 89 },
      LT:       { display: "J. Hudson III",  initials: "JH", ringType: "ol", badgeType: "ol",   badgeLabel: "LT",       headshot: "Hudson_James.jpg",         maxWidth: 36, rating: 63 },
      LG:       { display: "A. Vera-Tucker", initials: "AV", ringType: "ol", badgeType: "ol",   badgeLabel: "LG",       headshot: "Vera-Tucker_Alijah.jpg",   maxWidth: 36, rating: 83 },
      C:        { display: "B. Brown",       initials: "BB", ringType: "ol", badgeType: "ol",   badgeLabel: "C",        headshot: "Brown_Ben.jpg",            maxWidth: 36, rating: 65 },
      RG:       { display: "M. Onwenu",      initials: "MO", ringType: "ol", badgeType: "ol",   badgeLabel: "RG",       headshot: "Onwenu_Mike.jpg",          maxWidth: 36, rating: 86 },
      RT:       { display: "M. Moses",       initials: "MM", ringType: "ol", badgeType: "ol",   badgeLabel: "RT",       headshot: "Moses_Morgan.jpg",         maxWidth: 36, rating: 82 },
      TE:       { display: "H. Henry",       initials: "HH", ringType: "te", badgeType: "te",   badgeLabel: "TE",       headshot: "Henry_Hunter.jpg",         maxWidth: 36, rating: 86 },
      SLOT:     { display: "E. Chism III",   initials: "EC", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT",     headshot: "Chism_Efton.jpg",          rating: 68 },
      WR_RIGHT: { display: "M. Hollins",     initials: "MH", ringType: "wr", badgeType: "wr",   badgeLabel: "WR",       headshot: "Hollins_Mack.jpg",         rating: 77 },
      QB:       { display: "D. Maye",        initials: "DM", ringType: "qb", badgeType: "qb",   badgeLabel: "QB · #10", headshot: "Maye_Drake.jpg",   nameBold: true, rating: 93 },
      RB:       { display: "R. Stevenson",   initials: "RS", ringType: "rb", badgeType: "rb",   badgeLabel: "RB · #38", headshot: "Stevenson_Rhamondre.jpg",  rating: 77 },
    },
    defense: {
      CB_LEFT: { display: "C. Davis",    initials: "CD", ringType: "cb",  badgeType: "cb",  badgeLabel: "CB · #7",   headshot: "Davis_Carlton.jpg",      rating: 85 },
      SS:      { display: "K. Byard",    initials: "KB", ringType: "ss",  badgeType: "ss",  badgeLabel: "SS · #31",  headshot: "Byard_Kevin.jpg",        rating: 84 },
      FS:      { display: "C. Gonzalez", initials: "CG", ringType: "cb",  badgeType: "cb",  badgeLabel: "CB · #0",   headshot: "Gonzalez_Christian.jpg", rating: 98 },
      NB:      { display: "M. Jones",    initials: "MJ", ringType: "nb",  badgeType: "nb",  badgeLabel: "NB · #25",  headshot: "Jones_Marcus.jpg",       rating: 82 },
      OLB_L:   { display: "R. Spillane", initials: "RS", ringType: "lb",  badgeType: "lb",  badgeLabel: "OLB · #14", headshot: "Spillane_Robert.jpg",    rating: 85 },
      ILB_L:   { display: "K.J. Britt",  initials: "KB", ringType: "lb",  badgeType: "lb",  badgeLabel: "ILB · #35", headshot: "Britt_KJ.jpg",           rating: 71 },
      ILB_R:   { display: "C. Muma",     initials: "CM", ringType: "mlb", badgeType: "mlb", badgeLabel: "ILB · #49", headshot: "Muma_Chad.jpg",          rating: 70 },
      OLB_R:   { display: "D. Jones",    initials: "DJ", ringType: "lb",  badgeType: "lb",  badgeLabel: "OLB · #5",  headshot: "Jones_DReMont.jpg",      rating: 75 },
      DE_L:    { display: "C. Barmore",  initials: "CB", ringType: "de",  badgeType: "de",  badgeLabel: "LDE · #90", headshot: "Barmore_Christian.jpg",  rating: 79 },
      NT:      { display: "C. Durden",   initials: "CD", ringType: "dt",  badgeType: "dt",  badgeLabel: "NT · #94",  headshot: "Durden_Cory.jpg",        rating: 68 },
      DE_R:    { display: "H. Landry",   initials: "HL", ringType: "de",  badgeType: "de",  badgeLabel: "RDE · #2",  headshot: "Landry_Harold.jpg",      rating: 82 },
    },
  },

  // ── SEA — home ─────────────────────────────────────────────────────────────
  home: {
    name: "SEAHAWKS",
    abbr: "SEA",
    color: "#69BE28",
    logo: "/headshots/logo_sea.png",
    formation: "Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Hybrid",
    defScheme: "3-4 Hybrid",
    defDescription: "Seattle's Mike Macdonald scheme features a three-man DL anchored by Leonard Williams and DeMarcus Lawrence, with Devon Witherspoon as a versatile CB/LB hybrid. Primary coverage is Cover 3 zone with safety bracket help over the top. Aggressive blitz packages off the edge.",
    offense: {
      WR_LEFT:  { display: "JSN",           initials: "JN", ringType: "wr", badgeType: "wr",   badgeLabel: "WR",       headshot: "Smith-Njigba_Jaxon.jpg", rating: 95 },
      LT:       { display: "C. Cross",      initials: "CC", ringType: "ol", badgeType: "ol",   badgeLabel: "LT",       headshot: "Cross_Charles.jpg",      maxWidth: 36, rating: 83 },
      LG:       { display: "J. Sundell",    initials: "JS", ringType: "ol", badgeType: "ol",   badgeLabel: "LG",       headshot: "Sundell_Jalen.jpg",      maxWidth: 36, rating: 69 },
      C:        { display: "O. Oluwatimi",  initials: "OO", ringType: "ol", badgeType: "ol",   badgeLabel: "C",        headshot: "Oluwatimi_Olu.jpg",      maxWidth: 36, rating: 66 },
      RG:       { display: "A. Bradford",   initials: "AB", ringType: "ol", badgeType: "ol",   badgeLabel: "RG",       headshot: "Bradford_Anthony.jpg",   maxWidth: 36, rating: 72 },
      RT:       { display: "A. Lucas",      initials: "AL", ringType: "ol", badgeType: "ol",   badgeLabel: "RT",       headshot: "Lucas_Abraham.jpg",      maxWidth: 36, rating: 83 },
      TE:       { display: "AJ Barner",     initials: "AB", ringType: "te", badgeType: "te",   badgeLabel: "TE",       headshot: "Barner_AJ.jpg",          maxWidth: 36, rating: 75 },
      SLOT:     { display: "R. Shaheed",    initials: "RS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT",     headshot: "Shaheed_Rashid.jpg",     rating: 79 },
      WR_RIGHT: { display: "C. Kupp",       initials: "CK", ringType: "wr", badgeType: "wr",   badgeLabel: "WR",       headshot: "Kupp_Cooper.jpg",        rating: 84 },
      QB:       { display: "S. Darnold",    initials: "SD", ringType: "qb", badgeType: "qb",   badgeLabel: "QB · #14", headshot: "Darnold_Sam.jpg",  nameBold: true, rating: 85 },
      RB:       { display: "Z. Charbonnet", initials: "ZC", ringType: "rb", badgeType: "rb",   badgeLabel: "RB · #26", headshot: "Charbonnet_Zach.jpg",    rating: 82 },
    },
    defense: {
      CB_LEFT: { display: "J. Jobe",        initials: "JJ", ringType: "cb",  badgeType: "cb",  badgeLabel: "CB · #29",  headshot: "Jobe_Josh.jpg",         rating: 77 },
      SS:      { display: "J. Love",        initials: "JL", ringType: "ss",  badgeType: "ss",  badgeLabel: "SS · #20",  headshot: "Love_Julian.jpg",       rating: 85 },
      FS:      { display: "D. Bell",        initials: "DB", ringType: "fs",  badgeType: "fs",  badgeLabel: "FS · #23",  headshot: "Bell_D'Anthony.jpg",    rating: 70 },
      NB:      { display: "B. Clark",       initials: "BC", ringType: "nb",  badgeType: "nb",  badgeLabel: "NB · #9",   headshot: "Clark_Bud.jpg",         rating: 68 },
      OLB_L:   { display: "D. Witherspoon", initials: "DW", ringType: "lb",  badgeType: "lb",  badgeLabel: "SLB · #21", headshot: "Witherspoon_Devon.jpg", rating: 91 },
      ILB_L:   { display: "D. Thomas",      initials: "DT", ringType: "lb",  badgeType: "lb",  badgeLabel: "OLB · #32", headshot: "Thomas_Drake.jpg",      rating: 75 },
      ILB_R:   { display: "E. Jones",       initials: "EJ", ringType: "mlb", badgeType: "mlb", badgeLabel: "ILB · #13", headshot: "Jones_Ernest.jpg",      rating: 83 },
      OLB_R:   { display: "U. Nwosu",       initials: "UN", ringType: "lb",  badgeType: "lb",  badgeLabel: "ILB · #7",  headshot: "Nwosu_Uchenna.jpg",     rating: 77 },
      DE_L:    { display: "L. Williams",    initials: "LW", ringType: "de",  badgeType: "de",  badgeLabel: "LDE · #99", headshot: "Williams_Leonard.jpg",  rating: 88 },
      NT:      { display: "J. Reed",        initials: "JR", ringType: "dt",  badgeType: "dt",  badgeLabel: "NT · #90",  headshot: "Reed_Jarran.jpg",       rating: 78 },
      DE_R:    { display: "D. Lawrence",    initials: "DL", ringType: "de",  badgeType: "de",  badgeLabel: "RDE · #0",  headshot: "Lawrence_DeMarcus.jpg", rating: 87 },
    },
  },

  matchupSummary: {
    grades: [
      {
        label: "Pass Protection",
        awayGrade: "C-",
        homeGrade: "A",
        note: "NE's patchwork OLine (avg 75.8) faces D. Witherspoon (91) off the edge — pressure expected inside the first two drives",
      },
      {
        label: "QB vs Pass Rush",
        awayGrade: "A",
        homeGrade: "C-",
        note: "D. Maye (93) vs D. Witherspoon (91) — QB faces elite edge pressure",
      },
      {
        label: "WR1 vs CB1",
        awayGrade: "C-",
        homeGrade: "A",
        note: "JSN (95) vs C. Davis (85) — individual star matchup defines this position battle",
      },
      {
        label: "TE Matchup",
        awayGrade: "A",
        homeGrade: "C-",
        note: "H. Henry (86) exploits mismatches — SEA's inside linebackers (avg 79.0) are overmatched in coverage",
      },
      {
        label: "RB in Space",
        awayGrade: "C-",
        homeGrade: "A",
        note: "Z. Charbonnet (82) vs K.J. Britt (71) — RB in space and catching out of backfield",
      },
    ],
    verdict: "SEA defending champs at home — but Maye and Henry create real mismatches in the passing game",
  },
};
