import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "no-det",
  away: {
    name: "New Orleans Saints",
    abbr: "NO",
    color: "#101820",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "C. Olave", initials: "CO", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 86 },
      LT:       { display: "T. Penning", initials: "TP", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 78, maxWidth: 36 },
      LG:       { display: "L. Patrick", initials: "LP", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 72, maxWidth: 36 },
      C:        { display: "E. McCoy", initials: "EM", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 89, maxWidth: 36 },
      RG:       { display: "C. Ruiz", initials: "CR", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 80, maxWidth: 36 },
      RT:       { display: "J. Hurst", initials: "JH", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 74, maxWidth: 36 },
      TE:       { display: "J. Johnson", initials: "JJ", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 76 },
      SLOT:     { display: "B. Cooks", initials: "BC", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 79 },
      WR_RIGHT: { display: "M. Callaway", initials: "MC", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 71 },
      QB:       { display: "T. Shough", initials: "TS", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 68, nameBold: true },
      RB:       { display: "A. Kamara", initials: "AK", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 84 },
    },
    defense: {
      CB_LEFT: { display: "M. Lattimore", initials: "ML", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 84 },
      SS:      { display: "J. Howden", initials: "JH", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 72 },
      FS:      { display: "P. Williams", initials: "PW", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 72 },
      NB:      { display: "A. Taylor", initials: "AT", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "C. Jordan", initials: "CJ", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 84 },
      ILB_L:   { display: "D. Davis", initials: "DD", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 90, nameBold: true },
      ILB_R:   { display: "P. Werner", initials: "PW", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 },
      OLB_R:   { display: "C. Granderson", initials: "CG", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 },
      DE_L:    { display: "B. Bresee", initials: "BB", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 79 },
      NT:      { display: "K. Saunders", initials: "KS", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 },
      DE_R:    { display: "N. Shepherd", initials: "NS", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 73 },
    },
  },
  home: {
    name: "Detroit Lions",
    abbr: "DET",
    color: "#0076B6",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "A. St. Brown", initials: "AS", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 96, nameBold: true },
      LT:       { display: "P. Sewell", initials: "PS", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 97, maxWidth: 36, nameBold: true },
      LG:       { display: "K. Zeitler", initials: "KZ", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 84, maxWidth: 36 },
      C:        { display: "F. Ragnow", initials: "FR", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 92, maxWidth: 36, nameBold: true },
      RG:       { display: "G. Glasgow", initials: "GG", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 78, maxWidth: 36 },
      RT:       { display: "B. Miller", initials: "BM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 72, maxWidth: 36 },
      TE:       { display: "S. LaPorta", initials: "SL", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 87 },
      SLOT:     { display: "T. Patrick", initials: "TP", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "J. Williams", initials: "JW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 84 },
      QB:       { display: "J. Goff", initials: "JG", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 88, nameBold: true },
      RB:       { display: "J. Gibbs", initials: "JG", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 95, nameBold: true },
    },
    defense: {
      CB_LEFT: { display: "E. Moseley", initials: "EM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 72 },
      SS:      { display: "B. Branch", initials: "BB", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 89 },
      FS:      { display: "K. Joseph", initials: "KJ", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 90, nameBold: true },
      NB:      { display: "J. Jacobs", initials: "JJ", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "A. Hutchinson", initials: "AH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 93, nameBold: true },
      ILB_L:   { display: "A. Anzalone", initials: "AA", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      ILB_R:   { display: "J. Campbell", initials: "JC", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 80 },
      OLB_R:   { display: "M. Davenport", initials: "MD", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 },
      DE_L:    { display: "I. Buggs", initials: "IB", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
      NT:      { display: "A. McNeill", initials: "AM", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 82 },
      DE_R:    { display: "D. Reader", initials: "DR", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 80 },
    },
  },
};
