import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "nyj-ten",
  away: {
    name: "New York Jets",
    abbr: "NYJ",
    color: "#125740",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 2 Zone",
    defScheme: "3-4 Base",
    defDescription: "Sauce Gardner (94 OVR) is the best pure corner in football and New York's defensive anchor. Quinnen Williams (88 OVR) is a dominant interior pass rusher at 3-tech. Haason Reddick provides pressure off the edge. C.J. Mosley and Quincy Williams patrol the middle in Cover 2 zone with Sauce locking down in press man.",
    offense: {
      WR_LEFT:  { display: "G. Wilson", initials: "GW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 86 , headshot: "Wilson_Garrett.jpg" },
      LT:       { display: "M. Moses", initials: "MM", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 82, maxWidth: 36 , headshot: "Moses_Morgan.jpg" },
      LG:       { display: "L. Tomlinson", initials: "LT", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 80, maxWidth: 36 , headshot: "Tomlinson_Laken.jpg" },
      C:        { display: "J. Tippmann", initials: "JT", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 83, maxWidth: 36 , headshot: "Tippmann_Joe.jpg" },
      RG:       { display: "W. Schweitzer", initials: "WS", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 73, maxWidth: 36 },
      RT:       { display: "M. Mitchell", initials: "MM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 74, maxWidth: 36 , headshot: "Mitchell_Max.jpg" },
      TE:       { display: "T. Conklin", initials: "TC", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 75 , headshot: "Conklin_Tyler.jpg" },
      SLOT:     { display: "M. Corley", initials: "MC", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 , headshot: "Corley_Malachi.jpg" },
      WR_RIGHT: { display: "A. Lazard", initials: "AL", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 73 , headshot: "Lazard_Allen.jpg" },
      QB:       { display: "G. Smith", initials: "GS", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 71, nameBold: true , headshot: "Smith_Geno.jpg" },
      RB:       { display: "B. Hall", initials: "BH", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 80 , headshot: "Hall_Breece.jpg" },
    },
    defense: {
      CB_LEFT: { display: "S. Gardner", initials: "SG", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 94, nameBold: true , headshot: "Gardner_Sauce.jpg" },
      SS:      { display: "T. Adams", initials: "TA", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 74 , headshot: "Adams_Tony.jpg" },
      FS:      { display: "C. Clark", initials: "CC", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 73 , headshot: "Clark_Chuck.jpg" },
      NB:      { display: "M. Carter II", initials: "MC", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 , headshot: "Carter II_Michael.jpg" },
      OLB_L:   { display: "W. McDonald IV", initials: "WM", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 , headshot: "McDonald IV_Will.jpg" },
      ILB_L:   { display: "Q. Williams", initials: "QW", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 79 , headshot: "Williams_Quincy.jpg" },
      ILB_R:   { display: "C. Mosley", initials: "CM", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 82 , headshot: "Mosley_C.J..jpg" },
      OLB_R:   { display: "H. Reddick", initials: "HR", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 84 , headshot: "Reddick_Haason.jpg" },
      DE_L:    { display: "J. Franklin-Myers", initials: "JF", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 , headshot: "Franklin-Myers_John.jpg" },
      NT:      { display: "A. Woods", initials: "AW", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 , headshot: "Woods_Al.jpg" },
      DE_R:    { display: "Q. Williams", initials: "QW", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 88 , headshot: "Williams_Quinnen.jpg" },
    },
  },
  home: {
    name: "Tennessee Titans",
    abbr: "TEN",
    color: "#0C2340",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Tennessee's 4-3 is built around Jeffery Simmons (95 OVR) — the first-team All-Pro DT who broke the franchise sack record in 2025. L'Jarius Sneed (88 OVR) plays shadow corner. Azeez Al-Shaair is an instinctive ILB. Cover 3 zone with Amani Hooker as the run-support safety. Simple but effective.",
    offense: {
      WR_LEFT:  { display: "C. Ridley", initials: "CR", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 82 , headshot: "Ridley_Calvin.jpg" },
      LT:       { display: "J. Latham", initials: "JL", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 80, maxWidth: 36 , headshot: "Latham_JC.jpg" },
      LG:       { display: "P. Skoronski", initials: "PS", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 82, maxWidth: 36 , headshot: "Skoronski_Peter.jpg" },
      C:        { display: "L. Cushenberry", initials: "LC", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 , headshot: "Cushenberry_Lloyd.jpg" },
      RG:       { display: "D. Radunz", initials: "DR", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 74, maxWidth: 36 , headshot: "Radunz_Dillon.jpg" },
      RT:       { display: "N. Petit-Frere", initials: "NP", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 76, maxWidth: 36 , headshot: "Petit-Frere_Nicholas.jpg" },
      TE:       { display: "C. Okonkwo", initials: "CO", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 79 , headshot: "Okonkwo_Chigoziem.jpg" },
      SLOT:     { display: "N. Westbrook-Ikhine", initials: "NW", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 73 , headshot: "Westbrook-Ikhine_Nick.jpg" },
      WR_RIGHT: { display: "T. Boyd", initials: "TB", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 76 , headshot: "Boyd_Tyler.jpg" },
      QB:       { display: "C. Ward", initials: "CW", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true , headshot: "Ward_Cam.jpg" },
      RB:       { display: "T. Pollard", initials: "TP", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 83 , headshot: "Pollard_Tony.jpg" },
    },
    defense: {
      CB_LEFT: { display: "L. Sneed", initials: "LS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 88 , headshot: "Sneed_L'Jarius.jpg" },
      SS:      { display: "A. Hooker", initials: "AH", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 78 , headshot: "Hooker_Amani.jpg" },
      FS:      { display: "E. Molden", initials: "EM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 , headshot: "Molden_Elijah.jpg" },
      NB:      { display: "C. Farley", initials: "CF", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 73 , headshot: "Farley_Caleb.jpg" },
      OLB_L:   { display: "A. Key", initials: "AK", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 75 , headshot: "Key_Arden.jpg" },
      ILB_L:   { display: "A. Al-Shaair", initials: "AA", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 81 , headshot: "Al-Shaair_Azeez.jpg" },
      ILB_R:   { display: "L. Gifford", initials: "LG", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 72 , headshot: "Gifford_Luke.jpg" },
      OLB_R:   { display: "A. Quinn", initials: "AQ", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 72 },
      DE_L:    { display: "J. Simmons", initials: "JS", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 95, nameBold: true , headshot: "Simmons_Jeffery.jpg" },
      NT:      { display: "S. Joseph-Day", initials: "SJ", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 76 , headshot: "Joseph-Day_Sebastian.jpg" },
      DE_R:    { display: "S. Okuayinonu", initials: "SO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 70 , headshot: "Okuayinonu_Sam.jpg" },
    },
  },
  matchupSummary: {
    grades: [
      {
        label: "WR1 vs CB1",
        awayGrade: "A",
        homeGrade: "C-",
        note: "J. Simmons (95) at NT vs NYJ's interior — dominant presence that makes TEN's defense legitimately scary all game",
      },
    ],
    verdict: "Saleh's revenge game — lowest total of Week 1 (39.5), defensive grind, Titans win at home",
  },
};
