import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "nyj-ten",
  away: {
    name: "New York Jets",
    abbr: "NYJ",
    color: "#125740",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 2 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "G. Wilson", initials: "GW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 86 },
      LT:       { display: "M. Moses", initials: "MM", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 82, maxWidth: 36 },
      LG:       { display: "L. Tomlinson", initials: "LT", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 80, maxWidth: 36 },
      C:        { display: "J. Tippmann", initials: "JT", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 83, maxWidth: 36 },
      RG:       { display: "W. Schweitzer", initials: "WS", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 73, maxWidth: 36 },
      RT:       { display: "M. Mitchell", initials: "MM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 74, maxWidth: 36 },
      TE:       { display: "T. Conklin", initials: "TC", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 75 },
      SLOT:     { display: "M. Corley", initials: "MC", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "A. Lazard", initials: "AL", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 73 },
      QB:       { display: "G. Smith", initials: "GS", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 71, nameBold: true },
      RB:       { display: "B. Hall", initials: "BH", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 80 },
    },
    defense: {
      CB_LEFT: { display: "S. Gardner", initials: "SG", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 94, nameBold: true },
      SS:      { display: "T. Adams", initials: "TA", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 74 },
      FS:      { display: "C. Clark", initials: "CC", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 73 },
      NB:      { display: "M. Carter II", initials: "MC", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "W. McDonald IV", initials: "WM", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 78 },
      ILB_L:   { display: "Q. Williams", initials: "QW", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 79 },
      ILB_R:   { display: "C. Mosley", initials: "CM", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 82 },
      OLB_R:   { display: "H. Reddick", initials: "HR", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 84 },
      DE_L:    { display: "J. Franklin-Myers", initials: "JF", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 },
      NT:      { display: "A. Woods", initials: "AW", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 72 },
      DE_R:    { display: "Q. Williams", initials: "QW", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 88 },
    },
  },
  home: {
    name: "Tennessee Titans",
    abbr: "TEN",
    color: "#0C2340",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "C. Ridley", initials: "CR", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 82 },
      LT:       { display: "J. Latham", initials: "JL", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 80, maxWidth: 36 },
      LG:       { display: "P. Skoronski", initials: "PS", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 82, maxWidth: 36 },
      C:        { display: "L. Cushenberry", initials: "LC", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "D. Radunz", initials: "DR", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 74, maxWidth: 36 },
      RT:       { display: "N. Petit-Frere", initials: "NP", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 76, maxWidth: 36 },
      TE:       { display: "C. Okonkwo", initials: "CO", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 79 },
      SLOT:     { display: "N. Westbrook-Ikhine", initials: "NW", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 73 },
      WR_RIGHT: { display: "T. Boyd", initials: "TB", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 76 },
      QB:       { display: "C. Ward", initials: "CW", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true },
      RB:       { display: "T. Pollard", initials: "TP", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 83 },
    },
    defense: {
      CB_LEFT: { display: "L. Sneed", initials: "LS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 88 },
      SS:      { display: "A. Hooker", initials: "AH", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 78 },
      FS:      { display: "E. Molden", initials: "EM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 },
      NB:      { display: "C. Farley", initials: "CF", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 73 },
      OLB_L:   { display: "A. Key", initials: "AK", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 75 },
      ILB_L:   { display: "A. Al-Shaair", initials: "AA", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 81 },
      ILB_R:   { display: "L. Gifford", initials: "LG", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 72 },
      OLB_R:   { display: "A. Quinn", initials: "AQ", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 72 },
      DE_L:    { display: "J. Simmons", initials: "JS", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 95, nameBold: true },
      NT:      { display: "S. Joseph-Day", initials: "SJ", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 76 },
      DE_R:    { display: "S. Okuayinonu", initials: "SO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 70 },
    },
  },
};
