import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "sf-lar",
  away: {
    name: "San Francisco 49ers",
    abbr: "SF",
    color: "#AA0000",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "M. Evans", initials: "ME", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 },
      LT:       { display: "T. Williams", initials: "TW", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 97, maxWidth: 36, nameBold: true },
      LG:       { display: "A. Banks", initials: "AB", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 83, maxWidth: 36 },
      C:        { display: "J. Brendel", initials: "JB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 },
      RG:       { display: "D. Puni", initials: "DP", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 72, maxWidth: 36 },
      RT:       { display: "C. McKivitz", initials: "CM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 71, maxWidth: 36 },
      TE:       { display: "G. Kittle", initials: "GK", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 97, nameBold: true },
      SLOT:     { display: "D. Stribling", initials: "DS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 73 },
      WR_RIGHT: { display: "R. Pearsall", initials: "RP", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 76 },
      QB:       { display: "B. Purdy", initials: "BP", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 88, nameBold: true },
      RB:       { display: "J. Mason", initials: "JM", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 76 },
    },
    defense: {
      CB_LEFT: { display: "D. Lenoir", initials: "DL", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 79 },
      SS:      { display: "J. Brown", initials: "JB", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 72 },
      FS:      { display: "M. Mustapha", initials: "MM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 },
      NB:      { display: "R. Green", initials: "RG", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 70 },
      OLB_L:   { display: "N. Bosa", initials: "NB", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 97, nameBold: true },
      ILB_L:   { display: "D. Greenlaw", initials: "DG", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 80 },
      ILB_R:   { display: "F. Warner", initials: "FW", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 92, nameBold: true },
      OLB_R:   { display: "R. Beal Jr", initials: "RB", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 70 },
      DE_L:    { display: "A. Armstead", initials: "AA", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 82 },
      NT:      { display: "M. Collins", initials: "MC", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 74 },
      DE_R:    { display: "K. Givens", initials: "KG", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 },
    },
  },
  home: {
    name: "Los Angeles Rams",
    abbr: "LAR",
    color: "#003594",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "P. Nacua", initials: "PN", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 97, nameBold: true },
      LT:       { display: "A. Jackson", initials: "AJ", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 79, maxWidth: 36 },
      LG:       { display: "S. Avila", initials: "SA", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 86, maxWidth: 36 },
      C:        { display: "B. Allen", initials: "BA", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 78, maxWidth: 36 },
      RG:       { display: "J. Jackson", initials: "JJ", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 82, maxWidth: 36 },
      RT:       { display: "W. McClendon", initials: "WM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 73, maxWidth: 36 },
      TE:       { display: "T. Higbee", initials: "TH", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 },
      SLOT:     { display: "T. Atwell", initials: "TA", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 75 },
      WR_RIGHT: { display: "D. Adams", initials: "DA", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 },
      QB:       { display: "M. Stafford", initials: "MS", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true },
      RB:       { display: "K. Williams", initials: "KW", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 82 },
    },
    defense: {
      CB_LEFT: { display: "C. Durant", initials: "CD", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 78 },
      SS:      { display: "T. Moehrig", initials: "TM", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 78 },
      FS:      { display: "E. Scott Jr.", initials: "ES", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 72 },
      NB:      { display: "D. Kendrick", initials: "DK", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "B. Huff", initials: "BH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 82 },
      ILB_L:   { display: "C. Rozeboom", initials: "CR", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 72 },
      ILB_R:   { display: "J. Hummel", initials: "JH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 },
      OLB_R:   { display: "B. Young", initials: "BY", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 },
      DE_L:    { display: "K. Turner", initials: "KT", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 },
      NT:      { display: "A. Robinson", initials: "AR", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 76 },
      DE_R:    { display: "M. Hoecht", initials: "MH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 75 },
    },
  },
};
