import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "sf-lar",
  away: {
    name: "San Francisco 49ers",
    abbr: "SF",
    color: "#AA0000",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Nick Bosa anchors a 4-3 front that generates elite interior pressure. Fred Warner (92 OVR) quarterbacks the LB corps in Cover 3 zone, with Deommodore Lenoir and Renardo Green in off-coverage. The 49ers funnel everything to the middle and rely on Warner to clean it up.",
    offense: {
      WR_LEFT:  { display: "M. Evans", initials: "ME", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 , headshot: "Evans_Mike.jpg" },
      LT:       { display: "T. Williams", initials: "TW", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 97, maxWidth: 36, nameBold: true , headshot: "Williams_Trent.jpg" },
      LG:       { display: "A. Banks", initials: "AB", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 83, maxWidth: 36 , headshot: "Banks_Aaron.jpg" },
      C:        { display: "J. Brendel", initials: "JB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 74, maxWidth: 36 , headshot: "Brendel_Jake.jpg" },
      RG:       { display: "D. Puni", initials: "DP", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 72, maxWidth: 36 , headshot: "Puni_Dominick.jpg" },
      RT:       { display: "C. McKivitz", initials: "CM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 71, maxWidth: 36 , headshot: "McKivitz_Colton.jpg" },
      TE:       { display: "G. Kittle", initials: "GK", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 97, nameBold: true , headshot: "Kittle_George.jpg" },
      SLOT:     { display: "D. Stribling", initials: "DS", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 73 , headshot: "Stribling_De'Zhaun.jpg" },
      WR_RIGHT: { display: "R. Pearsall", initials: "RP", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 76 , headshot: "Pearsall_Ricky.jpg" },
      QB:       { display: "B. Purdy", initials: "BP", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 88, nameBold: true , headshot: "Purdy_Brock.jpg" },
      RB:       { display: "J. Mason", initials: "JM", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 76 , headshot: "Mason_Jordan.jpg" },
    },
    defense: {
      CB_LEFT: { display: "D. Lenoir", initials: "DL", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 79 , headshot: "Lenoir_Deommodore.jpg" },
      SS:      { display: "J. Brown", initials: "JB", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 72 , headshot: "Brown_Ji'Ayir.jpg" },
      FS:      { display: "M. Mustapha", initials: "MM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 74 , headshot: "Mustapha_Malik.jpg" },
      NB:      { display: "R. Green", initials: "RG", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 70 , headshot: "Green_Renardo.jpg" },
      OLB_L:   { display: "N. Bosa", initials: "NB", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 97, nameBold: true , headshot: "Bosa_Nick.jpg" },
      ILB_L:   { display: "D. Greenlaw", initials: "DG", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 80 , headshot: "Greenlaw_Dre.jpg" },
      ILB_R:   { display: "F. Warner", initials: "FW", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 92, nameBold: true , headshot: "Warner_Fred.jpg" },
      OLB_R:   { display: "R. Beal Jr", initials: "RB", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 70 , headshot: "Beal Jr_Robert.jpg" },
      DE_L:    { display: "A. Armstead", initials: "AA", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 82 , headshot: "Armstead_Arik.jpg" },
      NT:      { display: "M. Collins", initials: "MC", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 74 , headshot: "Collins_Maliek.jpg" },
      DE_R:    { display: "K. Givens", initials: "KG", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 72 , headshot: "Givens_Kevin.jpg" },
    },
  },
  home: {
    name: "Los Angeles Rams",
    abbr: "LAR",
    color: "#003594",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    defDescription: "The Rams run a 3-4 base under Sean McVay's defensive staff, with Bryce Huff as the primary edge rusher off the left side. Cover 3 zone underneath with safeties Tre'Von Moehrig and Eric Scott Jr. splitting deep thirds. Kobie Turner provides interior push as the 3-tech.",
    offense: {
      WR_LEFT:  { display: "P. Nacua", initials: "PN", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 97, nameBold: true , headshot: "Nacua_Puka.jpg" },
      LT:       { display: "A. Jackson", initials: "AJ", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 79, maxWidth: 36 , headshot: "Jackson_Alaric.jpg" },
      LG:       { display: "S. Avila", initials: "SA", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 86, maxWidth: 36 , headshot: "Avila_Steve.jpg" },
      C:        { display: "B. Allen", initials: "BA", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 78, maxWidth: 36 , headshot: "Allen_Brian.jpg" },
      RG:       { display: "J. Jackson", initials: "JJ", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 82, maxWidth: 36 , headshot: "Jackson_Jonah.jpg" },
      RT:       { display: "W. McClendon", initials: "WM", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 73, maxWidth: 36 },
      TE:       { display: "T. Higbee", initials: "TH", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 , headshot: "Higbee_Tyler.jpg" },
      SLOT:     { display: "T. Atwell", initials: "TA", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 75 , headshot: "Atwell_Tutu.jpg" },
      WR_RIGHT: { display: "D. Adams", initials: "DA", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 88 , headshot: "Adams_Davante.jpg" },
      QB:       { display: "M. Stafford", initials: "MS", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true , headshot: "Stafford_Matthew.jpg" },
      RB:       { display: "K. Williams", initials: "KW", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 82 , headshot: "Williams_Kyren.jpg" },
    },
    defense: {
      CB_LEFT: { display: "C. Durant", initials: "CD", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 78 , headshot: "Durant_Cobie.jpg" },
      SS:      { display: "T. Moehrig", initials: "TM", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 78 , headshot: "Moehrig_Tre'Von.jpg" },
      FS:      { display: "E. Scott Jr.", initials: "ES", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 72 },
      NB:      { display: "D. Kendrick", initials: "DK", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 , headshot: "Kendrick_Derion.jpg" },
      OLB_L:   { display: "B. Huff", initials: "BH", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 82 },
      ILB_L:   { display: "C. Rozeboom", initials: "CR", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 72 , headshot: "Rozeboom_Christian.jpg" },
      ILB_R:   { display: "J. Hummel", initials: "JH", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 , headshot: "Hummel_Jake.jpg" },
      OLB_R:   { display: "B. Young", initials: "BY", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 , headshot: "Young_Byron.jpg" },
      DE_L:    { display: "K. Turner", initials: "KT", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 78 , headshot: "Turner_Kobie.jpg" },
      NT:      { display: "A. Robinson", initials: "AR", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 76 , headshot: "Robinson_A'Shawn.jpg" },
      DE_R:    { display: "M. Hoecht", initials: "MH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 75 , headshot: "Hoecht_Michael.jpg" },
    },
  },
};
