import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "tb-cin",
  away: {
    name: "Tampa Bay Buccaneers",
    abbr: "TB",
    color: "#D50A0A",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    defDescription: "Tampa Bay's 3-4 is built around Antoine Winfield Jr. (94 OVR) as the chess piece — lines up everywhere from box safety to near-line blitzer. Vita Vea (90 OVR) is an immovable 1-tech who demands double teams. Yaya Diaby generates edge pressure in Cover 3 zone with two-high safety looks.",
    offense: {
      WR_LEFT:  { display: "C. Godwin", initials: "CG", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 83 , headshot: "Godwin_Chris.jpg" },
      LT:       { display: "T. Wirfs", initials: "TW", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 94, maxWidth: 36, nameBold: true , headshot: "Wirfs_Tristan.jpg" },
      LG:       { display: "B. Bredeson", initials: "BB", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 74, maxWidth: 36 , headshot: "Bredeson_Ben.jpg" },
      C:        { display: "G. Barton", initials: "GB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 , headshot: "Barton_Graham.jpg" },
      RG:       { display: "C. Paul", initials: "CP", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 72, maxWidth: 36 , headshot: "Paul_Cody.jpg" },
      RT:       { display: "L. Goedeke", initials: "LG", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 76, maxWidth: 36 , headshot: "Goedeke_Luke.jpg" },
      TE:       { display: "C. Otton", initials: "CO", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 76 , headshot: "Otton_Cade.jpg" },
      SLOT:     { display: "J. McMillan", initials: "JM", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 , headshot: "McMillan_Jalen.jpg" },
      WR_RIGHT: { display: "S. Shepard", initials: "SS", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 72 , headshot: "Shepard_Sterling.jpg" },
      QB:       { display: "B. Mayfield", initials: "BM", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true , headshot: "Mayfield_Baker.jpg" },
      RB:       { display: "R. White", initials: "RW", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 77 , headshot: "White_Rachaad.jpg" },
    },
    defense: {
      CB_LEFT: { display: "T. Smith", initials: "TS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 72 , headshot: "Smith_Tykee.jpg" },
      SS:      { display: "A. Winfield Jr.", initials: "AW", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 94, nameBold: true , headshot: "Winfield Jr._Antoine.jpg" },
      FS:      { display: "K. Merriweather", initials: "KM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 72 , headshot: "Merriweather_Kaevon.jpg" },
      NB:      { display: "Z. McCollum", initials: "ZM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 , headshot: "McCollum_Zyon.jpg" },
      OLB_L:   { display: "Y. Diaby", initials: "YD", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 80 , headshot: "Diaby_Yaya.jpg" },
      ILB_L:   { display: "S. Dennis", initials: "SD", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 70 , headshot: "Dennis_SirVocea.jpg" },
      ILB_R:   { display: "J. Trotter", initials: "JT", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 72 , headshot: "Trotter_Josiah.jpg" },
      OLB_R:   { display: "M. Watts", initials: "MW", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 72 , headshot: "Watts_Markees.jpg" },
      DE_L:    { display: "V. Vea", initials: "VV", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 90, nameBold: true , headshot: "Vea_Vita.jpg" },
      NT:      { display: "C. Kancey", initials: "CK", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 80 , headshot: "Kancey_Calijah.jpg" },
      DE_R:    { display: "R. Bain Jr.", initials: "RB", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 74 , headshot: "Bain Jr._Rueben.jpg" },
    },
  },
  home: {
    name: "Cincinnati Bengals",
    abbr: "CIN",
    color: "#FB4F14",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    defDescription: "Cincinnati's 4-3 pairs Sam Hubbard and Joseph Ossai as bookend DEs with Calijah Kancey providing interior quickness. Dax Hill (79 OVR) is a versatile SS who can match up in man. Germaine Pratt and Logan Wilson man the middle in Cover 3, with DJ Turner as the nickel.",
    offense: {
      WR_LEFT:  { display: "J. Chase", initials: "JC", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 99, nameBold: true , headshot: "Chase_Ja'Marr.jpg" },
      LT:       { display: "O. Brown Jr.", initials: "OB", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 84, maxWidth: 36 , headshot: "Brown Jr._Orlando.jpg" },
      LG:       { display: "A. Cappa", initials: "AC", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 78, maxWidth: 36 , headshot: "Cappa_Alex.jpg" },
      C:        { display: "T. Karras", initials: "TK", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 , headshot: "Karras_Ted.jpg" },
      RG:       { display: "C. Volson", initials: "CV", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 76, maxWidth: 36 , headshot: "Volson_Cordell.jpg" },
      RT:       { display: "T. Brown", initials: "TB", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 78, maxWidth: 36 , headshot: "Brown_Trent.jpg" },
      TE:       { display: "M. Gesicki", initials: "MG", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 , headshot: "Gesicki_Mike.jpg" },
      SLOT:     { display: "C. Jones", initials: "CJ", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 , headshot: "Jones_Charlie.jpg" },
      WR_RIGHT: { display: "T. Higgins", initials: "TH", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 87 , headshot: "Higgins_Tee.jpg" },
      QB:       { display: "J. Burrow", initials: "JB", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 95, nameBold: true , headshot: "Burrow_Joe.jpg" },
      RB:       { display: "C. Brown", initials: "CB", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 78 , headshot: "Brown_Chase.jpg" },
    },
    defense: {
      CB_LEFT: { display: "C. Taylor-Britt", initials: "CT", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 78 , headshot: "Taylor-Britt_Cam.jpg" },
      SS:      { display: "D. Hill", initials: "DH", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 79 , headshot: "Hill_Dax.jpg" },
      FS:      { display: "V. Bell", initials: "VB", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 , headshot: "Bell_Vonn.jpg" },
      NB:      { display: "D. Turner", initials: "DT", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 , headshot: "Turner_DJ.jpg" },
      OLB_L:   { display: "M. Murphy", initials: "MM", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 79 , headshot: "Murphy_Myles.jpg" },
      ILB_L:   { display: "G. Pratt", initials: "GP", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 , headshot: "Pratt_Germaine.jpg" },
      ILB_R:   { display: "L. Wilson", initials: "LW", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 , headshot: "Wilson_Logan.jpg" },
      OLB_R:   { display: "S. Stewart", initials: "SS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 , headshot: "Stewart_Shemar.jpg" },
      DE_L:    { display: "S. Hubbard", initials: "SH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 82 },
      NT:      { display: "Z. Carter", initials: "ZC", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 74 , headshot: "Carter_Zach.jpg" },
      DE_R:    { display: "J. Ossai", initials: "JO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 , headshot: "Ossai_Joseph.jpg" },
    },
  },
  matchupSummary: {
    grades: [
      {
        label: "WR vs Secondary",
        awayGrade: "C-",
        homeGrade: "A",
        note: "J. Chase (99) vs Z. McCollum (74) — receiving corps tests the opposing secondary",
      },
      {
        label: "QB vs Pass Rush",
        awayGrade: "C-",
        homeGrade: "A",
        note: "J. Burrow (95) vs Y. Diaby (80) — QB faces elite edge pressure",
      },
      {
        label: "WR1 vs CB1",
        awayGrade: "C-",
        homeGrade: "A",
        note: "J. Chase (99) vs A. Winfield Jr. (94) bracket — analysts say Chase sees 140+ yards unless TB double-teams constantly",
      },
      {
        label: "RB in Space",
        awayGrade: "C-",
        homeGrade: "A",
        note: "C. Brown (78) vs J. Trotter (72) — RB in space and catching out of backfield",
      },
    ],
    verdict: "Highest total of Week 1 (50.5) — Burrow-Chase too dynamic, but Mayfield keeps it close through three quarters",
  },
};
