import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "tb-cin",
  away: {
    name: "Tampa Bay Buccaneers",
    abbr: "TB",
    color: "#D50A0A",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "C. Godwin", initials: "CG", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 83 },
      LT:       { display: "T. Wirfs", initials: "TW", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 94, maxWidth: 36, nameBold: true },
      LG:       { display: "B. Bredeson", initials: "BB", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 74, maxWidth: 36 },
      C:        { display: "G. Barton", initials: "GB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "C. Paul", initials: "CP", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 72, maxWidth: 36 },
      RT:       { display: "L. Goedeke", initials: "LG", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 76, maxWidth: 36 },
      TE:       { display: "C. Otton", initials: "CO", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 76 },
      SLOT:     { display: "J. McMillan", initials: "JM", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "S. Shepard", initials: "SS", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 72 },
      QB:       { display: "B. Mayfield", initials: "BM", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 82, nameBold: true },
      RB:       { display: "R. White", initials: "RW", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 77 },
    },
    defense: {
      CB_LEFT: { display: "T. Smith", initials: "TS", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 72 },
      SS:      { display: "A. Winfield Jr.", initials: "AW", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 94, nameBold: true },
      FS:      { display: "K. Merriweather", initials: "KM", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 72 },
      NB:      { display: "Z. McCollum", initials: "ZM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "Y. Diaby", initials: "YD", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 80 },
      ILB_L:   { display: "S. Dennis", initials: "SD", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 70 },
      ILB_R:   { display: "J. Trotter", initials: "JT", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 72 },
      OLB_R:   { display: "M. Watts", initials: "MW", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 72 },
      DE_L:    { display: "V. Vea", initials: "VV", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 90, nameBold: true },
      NT:      { display: "C. Kancey", initials: "CK", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 80 },
      DE_R:    { display: "R. Bain Jr.", initials: "RB", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 74 },
    },
  },
  home: {
    name: "Cincinnati Bengals",
    abbr: "CIN",
    color: "#FB4F14",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-3 Base — Cover 3 Zone",
    defScheme: "4-3 Base",
    offense: {
      WR_LEFT:  { display: "J. Chase", initials: "JC", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 99, nameBold: true },
      LT:       { display: "O. Brown Jr.", initials: "OB", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 84, maxWidth: 36 },
      LG:       { display: "A. Cappa", initials: "AC", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 78, maxWidth: 36 },
      C:        { display: "T. Karras", initials: "TK", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 76, maxWidth: 36 },
      RG:       { display: "C. Volson", initials: "CV", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 76, maxWidth: 36 },
      RT:       { display: "T. Brown", initials: "TB", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 78, maxWidth: 36 },
      TE:       { display: "M. Gesicki", initials: "MG", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 },
      SLOT:     { display: "C. Jones", initials: "CJ", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 74 },
      WR_RIGHT: { display: "T. Higgins", initials: "TH", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 87 },
      QB:       { display: "J. Burrow", initials: "JB", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 95, nameBold: true },
      RB:       { display: "C. Brown", initials: "CB", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 78 },
    },
    defense: {
      CB_LEFT: { display: "C. Taylor-Britt", initials: "CT", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 78 },
      SS:      { display: "D. Hill", initials: "DH", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 79 },
      FS:      { display: "V. Bell", initials: "VB", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 76 },
      NB:      { display: "D. Turner", initials: "DT", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "M. Murphy", initials: "MM", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 79 },
      ILB_L:   { display: "G. Pratt", initials: "GP", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 78 },
      ILB_R:   { display: "L. Wilson", initials: "LW", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 76 },
      OLB_R:   { display: "S. Stewart", initials: "SS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 74 },
      DE_L:    { display: "S. Hubbard", initials: "SH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 82 },
      NT:      { display: "Z. Carter", initials: "ZC", ringType: "dt", badgeType: "dt", badgeLabel: "DT", rating: 74 },
      DE_R:    { display: "J. Ossai", initials: "JO", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 76 },
    },
  },
};
