import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "was-phi",
  away: {
    name: "Washington Commanders",
    abbr: "WAS",
    color: "#5A1414",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-2-5 Nickel — Cover 3 Zone",
    defScheme: "4-2-5 Nickel",
    offense: {
      WR_LEFT:  { display: "T. McLaurin", initials: "TM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 94, nameBold: true },
      LT:       { display: "L. Tunsil", initials: "LT", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 95, maxWidth: 36, nameBold: true },
      LG:       { display: "A. Wylie", initials: "AW", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 73, maxWidth: 36 },
      C:        { display: "T. Biadasz", initials: "TB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 78, maxWidth: 36 },
      RG:       { display: "S. Cosmi", initials: "SC", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 87, maxWidth: 36 },
      RT:       { display: "C. Lucas", initials: "CL", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 74, maxWidth: 36 },
      TE:       { display: "Z. Ertz", initials: "ZE", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 },
      SLOT:     { display: "A. Williams", initials: "AW", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 },
      WR_RIGHT: { display: "D. Samuel", initials: "DS", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 81 },
      QB:       { display: "J. Daniels", initials: "JD", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 85, nameBold: true },
      RB:       { display: "R. White", initials: "RW", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 79 },
    },
    defense: {
      CB_LEFT: { display: "E. Forbes", initials: "EF", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 79 },
      SS:      { display: "B. Wagner", initials: "BW", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 92, nameBold: true },
      FS:      { display: "N. Cross", initials: "NC", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 78 },
      NB:      { display: "T. Amos", initials: "TA", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 },
      OLB_L:   { display: "O. Oweh", initials: "OO", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 80 },
      ILB_L:   { display: "S. Styles", initials: "SS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 },
      ILB_R:   { display: "J. Davis", initials: "JD", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 },
      OLB_R:   { display: "C. Toohill", initials: "CT", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 72 },
      DE_L:    { display: "D. Payne", initials: "DP", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 84 },
      NT:      { display: "J. Newton", initials: "JN", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 78 },
      DE_R:    { display: "P. Mathis", initials: "PM", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 73 },
    },
  },
  home: {
    name: "Philadelphia Eagles",
    abbr: "PHI",
    color: "#004C54",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    offense: {
      WR_LEFT:  { display: "D. Smith", initials: "DS", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 89 },
      LT:       { display: "J. Mailata", initials: "JM", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 96, maxWidth: 36, nameBold: true },
      LG:       { display: "L. Dickerson", initials: "LD", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 91, maxWidth: 36, nameBold: true },
      C:        { display: "C. Jurgens", initials: "CJ", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 84, maxWidth: 36 },
      RG:       { display: "M. Becton", initials: "MB", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 84, maxWidth: 36 },
      RT:       { display: "L. Johnson", initials: "LJ", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 99, maxWidth: 36, nameBold: true },
      TE:       { display: "D. Goedert", initials: "DG", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 87 },
      SLOT:     { display: "C. DeJean", initials: "CD", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 85 },
      WR_RIGHT: { display: "D. Wicks", initials: "DW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 77 },
      QB:       { display: "J. Hurts", initials: "JH", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 86, nameBold: true },
      RB:       { display: "S. Barkley", initials: "SB", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 99, nameBold: true },
    },
    defense: {
      CB_LEFT: { display: "Q. Mitchell", initials: "QM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 89 },
      SS:      { display: "A. Mukuba", initials: "AM", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 74 },
      FS:      { display: "M. Epps", initials: "ME", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 78 },
      NB:      { display: "R. Woolen", initials: "RW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 },
      OLB_L:   { display: "N. Smith", initials: "NS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 },
      ILB_L:   { display: "Z. Baun", initials: "ZB", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 88 },
      ILB_R:   { display: "J. Campbell", initials: "JC", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 },
      OLB_R:   { display: "J. Greenard", initials: "JG", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 85 },
      DE_L:    { display: "J. Carter", initials: "JC", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 89 },
      NT:      { display: "J. Davis", initials: "JD", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 80 },
      DE_R:    { display: "J. Hunt", initials: "JH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 73 },
    },
  },
};
