import type { GameMatchupData } from "@/lib/matchup-types";

export const GAME_DATA: GameMatchupData = {
  id: "was-phi",
  away: {
    name: "Washington Commanders",
    abbr: "WAS",
    color: "#5A1414",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "4-2-5 Nickel — Cover 3 Zone",
    defScheme: "4-2-5 Nickel",
    defDescription: "Washington's 4-2-5 nickel base is built around Bobby Wagner (92 OVR) playing at SS/LB hybrid — a veteran presence who makes every defensive call. Da'Ron Payne (84 OVR) is the interior anchor. Odafe Oweh provides edge pressure. Emmanuel Forbes plays Cover 3 zone with two safeties splitting deep halves.",
    offense: {
      WR_LEFT:  { display: "T. McLaurin", initials: "TM", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 94, nameBold: true , headshot: "McLaurin_Terry.jpg" },
      LT:       { display: "L. Tunsil", initials: "LT", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 95, maxWidth: 36, nameBold: true , headshot: "Tunsil_Laremy.jpg" },
      LG:       { display: "A. Wylie", initials: "AW", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 73, maxWidth: 36 , headshot: "Wylie_Andrew.jpg" },
      C:        { display: "T. Biadasz", initials: "TB", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 78, maxWidth: 36 , headshot: "Biadasz_Tyler.jpg" },
      RG:       { display: "S. Cosmi", initials: "SC", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 87, maxWidth: 36 , headshot: "Cosmi_Sam.jpg" },
      RT:       { display: "C. Lucas", initials: "CL", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 74, maxWidth: 36 , headshot: "Lucas_Cornelius.jpg" },
      TE:       { display: "Z. Ertz", initials: "ZE", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 78 , headshot: "Ertz_Zach.jpg" },
      SLOT:     { display: "A. Williams", initials: "AW", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 72 , headshot: "Williams_Antonio.jpg" },
      WR_RIGHT: { display: "D. Samuel", initials: "DS", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 81 },
      QB:       { display: "J. Daniels", initials: "JD", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 85, nameBold: true , headshot: "Daniels_Jayden.jpg" },
      RB:       { display: "R. White", initials: "RW", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 79 , headshot: "White_Rachaad.jpg" },
    },
    defense: {
      CB_LEFT: { display: "E. Forbes", initials: "EF", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 79 },
      SS:      { display: "B. Wagner", initials: "BW", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 92, nameBold: true , headshot: "Wagner_Bobby.jpg" },
      FS:      { display: "N. Cross", initials: "NC", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 78 , headshot: "Cross_Nick.jpg" },
      NB:      { display: "T. Amos", initials: "TA", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 74 , headshot: "Amos_Trey.jpg" },
      OLB_L:   { display: "O. Oweh", initials: "OO", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 80 , headshot: "Oweh_Odafe.jpg" },
      ILB_L:   { display: "S. Styles", initials: "SS", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 73 , headshot: "Styles_Sonny.jpg" },
      ILB_R:   { display: "J. Davis", initials: "JD", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 , headshot: "Davis_Jamin.jpg" },
      OLB_R:   { display: "C. Toohill", initials: "CT", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 72 },
      DE_L:    { display: "D. Payne", initials: "DP", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 84 , headshot: "Payne_Da'Ron.jpg" },
      NT:      { display: "J. Newton", initials: "JN", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 78 , headshot: "Newton_Jer'Zhan.jpg" },
      DE_R:    { display: "P. Mathis", initials: "PM", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 73 , headshot: "Mathis_Phidarian.jpg" },
    },
  },
  home: {
    name: "Philadelphia Eagles",
    abbr: "PHI",
    color: "#004C54",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
    formation: "11 Personnel · Shotgun",
    personnel: "11 Personnel",
    defFormation: "3-4 Base — Cover 3 Zone",
    defScheme: "3-4 Base",
    defDescription: "Philadelphia's 3-4 is elite. Jalen Carter (89 OVR) is a force of nature at 1-tech. Zack Baun (88 OVR) breaks out as the do-everything ILB. Jonathan Greenard (85 OVR) and Nolan Smith pressure off the edges. Quinyon Mitchell (89 OVR) is a lockdown boundary corner. Cover 3 zone with deep safety help.",
    offense: {
      WR_LEFT:  { display: "D. Smith", initials: "DS", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 89 , headshot: "Smith_DeVonta.jpg" },
      LT:       { display: "J. Mailata", initials: "JM", ringType: "ol", badgeType: "ol", badgeLabel: "LT", rating: 96, maxWidth: 36, nameBold: true , headshot: "Mailata_Jordan.jpg" },
      LG:       { display: "L. Dickerson", initials: "LD", ringType: "ol", badgeType: "ol", badgeLabel: "LG", rating: 91, maxWidth: 36, nameBold: true , headshot: "Dickerson_Landon.jpg" },
      C:        { display: "C. Jurgens", initials: "CJ", ringType: "ol", badgeType: "ol", badgeLabel: "C", rating: 84, maxWidth: 36 , headshot: "Jurgens_Cam.jpg" },
      RG:       { display: "M. Becton", initials: "MB", ringType: "ol", badgeType: "ol", badgeLabel: "RG", rating: 84, maxWidth: 36 },
      RT:       { display: "L. Johnson", initials: "LJ", ringType: "ol", badgeType: "ol", badgeLabel: "RT", rating: 99, maxWidth: 36, nameBold: true , headshot: "Johnson_Lane.jpg" },
      TE:       { display: "D. Goedert", initials: "DG", ringType: "te", badgeType: "te", badgeLabel: "TE", rating: 87 , headshot: "Goedert_Dallas.jpg" },
      SLOT:     { display: "C. DeJean", initials: "CD", ringType: "wr", badgeType: "slot", badgeLabel: "SLOT", rating: 85 , headshot: "DeJean_Cooper.jpg" },
      WR_RIGHT: { display: "D. Wicks", initials: "DW", ringType: "wr", badgeType: "wr", badgeLabel: "WR", rating: 77 , headshot: "Wicks_Dontayvion.jpg" },
      QB:       { display: "J. Hurts", initials: "JH", ringType: "qb", badgeType: "qb", badgeLabel: "QB", rating: 86, nameBold: true , headshot: "Hurts_Jalen.jpg" },
      RB:       { display: "S. Barkley", initials: "SB", ringType: "rb", badgeType: "rb", badgeLabel: "RB", rating: 99, nameBold: true , headshot: "Barkley_Saquon.jpg" },
    },
    defense: {
      CB_LEFT: { display: "Q. Mitchell", initials: "QM", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 89 , headshot: "Mitchell_Quinyon.jpg" },
      SS:      { display: "A. Mukuba", initials: "AM", ringType: "ss", badgeType: "ss", badgeLabel: "SS", rating: 74 , headshot: "Mukuba_Andrew.jpg" },
      FS:      { display: "M. Epps", initials: "ME", ringType: "fs", badgeType: "fs", badgeLabel: "FS", rating: 78 , headshot: "Epps_Marcus.jpg" },
      NB:      { display: "R. Woolen", initials: "RW", ringType: "cb", badgeType: "cb", badgeLabel: "CB", rating: 76 , headshot: "Woolen_Riq.jpg" },
      OLB_L:   { display: "N. Smith", initials: "NS", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 76 , headshot: "Smith_Nolan.jpg" },
      ILB_L:   { display: "Z. Baun", initials: "ZB", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 88 , headshot: "Baun_Zack.jpg" },
      ILB_R:   { display: "J. Campbell", initials: "JC", ringType: "lb", badgeType: "lb", badgeLabel: "ILB", rating: 74 , headshot: "Campbell_Jihaad.jpg" },
      OLB_R:   { display: "J. Greenard", initials: "JG", ringType: "lb", badgeType: "lb", badgeLabel: "OLB", rating: 85 , headshot: "Greenard_Jonathan.jpg" },
      DE_L:    { display: "J. Carter", initials: "JC", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 89 , headshot: "Carter_Jalen.jpg" },
      NT:      { display: "J. Davis", initials: "JD", ringType: "nt", badgeType: "nt", badgeLabel: "NT", rating: 80 },
      DE_R:    { display: "J. Hunt", initials: "JH", ringType: "de", badgeType: "de", badgeLabel: "DE", rating: 73 , headshot: "Hunt_Jalyx.jpg" },
    },
  },
};
